### ISSUE TITLE
bundleonly option does not check for errors

### ISSUE THREAD

**Issue by amieres** [dotnet-websharper/core#1000]
I have been trying out this feature. There are a couple of issues:

1.- Could we add command line options for `jsOutput` and `minJsOutput` so that wsconfig.json is not needed?
2.- when `project` is of type `bundleonly` wsfcs.exe ignores all errors and generates partial JavaScript code:

```
        module Hello
            open WebSharper
            [< assembly: JavaScriptExport >]
            do ()
            
            let run() = xxprintfn "Hello"
```
compiles as 
```
...
...
};
(function()
{
 "use strict";
 var Global,Hello;
 Global=self;
 Hello=Global.Hello=Global.Hello||{};
 Hello.run=function()
 {
  throw 1;
 };
}());

...
```

When there are more errors it simply compiles as `void 0;` plus the rest of the supporting code.

When project type is not `bundleonly` the compiler shows the correct error messages.

3.- Also `bundle` throws this error:

```
WebSharper translation: 00:00:00.5186946
WebSharper error FS9001: Global error 'An index satisfying the predicate was not found in the collection.' at    at Microsoft.FSharp.Collections.ListModule.Find[T](FSharpFunc`2 predicate, FSharpList`1 list)
   at WebSharper.Compiler.Bundling.AddExtraBundles(WsConfig config, FSharpList`1 refMetas, Info currentMeta, FSharpList`1 refAssemblies, Compilation comp, FSharpChoice`2 assem)
   at WebSharper.FSharp.Program.Compile$cont@218-3(WsConfig config, Loader loader, FSharpList`1 refs, Task`1 wsRefsMeta, Compilation comp, Info currentMeta, Unit unitVar)
 ...
```

Which goes away when either `netstandard.dll` or `mscorlib.dll` is included as a reference. (accompanied with --noframework)
Maybe the message should say so.

**Comment by Tarmil** [comment]
1. That would indeed be good, thanks for the suggestion.

2. Indeed, that is really weird, I'm investigating it.

3. Interestingly I get a different (but also bad) behavior: the compiler seemingly crashes earlier (after "Waiting on merged metadata: 00:00:00.0039895") without any error message. I'll also investigate this.

**Comment by Tarmil** [comment]
I just pushed a fix for 2.; this fix also gives me the following output for 3.:

```
parse error FS0084: Assembly reference 'mscorlib.dll' was not found or is invalid
```

so I would consider it fixed too.

I issued 1. separately as #1002, since it is a separate concern.

**Comment by amieres** [comment]
Excellent!, thank you very much.
