### ISSUE TITLE
Type constraints introduce indirection (performance hit) in the generated code

### ISSUE THREAD

**Issue by zpodlovics** [dotnet-websharper/core#1013]
Please consider the following code snippet to as an example implementation of LanguagePrimitives.EnumToValue and LanguagePrimitives.EnumOfValue. Unfortunately I am not yet able to build the project to test it and create a pull request with proper EnumOfValue / EnumToValue naming to extend src/stdlib/WebSharper.Main.Proxies/Operators.fs

```fsharp
[<JavaScript>]
module LanguageOperations = begin   
    [<Inline "$x" >]
    let toUInt8 (x: 'T) = X<uint8>

    [<Inline "$x" >]
    let ofUInt8<'T> (x: uint8) = X<'T>

end

[<JavaScript>]
module EnumOperations = begin

    [<Inline "$x" >]
    let inline enumOfValue< ^T,^U when ^U: enum< ^T>> (value: ^T) : ^U = X< ^U>
    [<Inline "$x" >]
    let inline enumToValue< ^T,^U when ^T: enum< ^U>> (value: ^T) : ^U = X< ^U>

end

type [<RequireQualifiedAccess; JavaScript>] Model =
    | CaseA = 1uy
    | CaseB = 2uy
    | CaseC = 3uy

```

```fsharp

[<JavaScript>]
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module Model = begin
    let ofValue (value: uint8) : Model = 
        LanguageOperations.ofUInt8 value

    let toValue (value: Model) : uint8 = 
        LanguageOperations.toUInt8 value

end
```

will generate the following code:

```javascript
 ModelModule.toValue=Global.id;
 ModelModule.ofValue=Global.id;
```

However the following code:

```fsharp
[<JavaScript>]
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module Model = begin

    let ofValue (value: uint8) : Model = 
        EnumOperations.enumOfValue<uint8,Model>(value)

    let toValue (value: Model) : uint8 = 
        EnumOperations.enumToValue<Model,uint8>(value)

end
```

Will introduce indirection (and a performance hit: ~25% in message codec) in the generated code:

```javascript
 ModelModule.toValue=function(value)
 {
  return Global.$x;
 };
 ModelModule.ofValue=function(value)
 {
  return Global.$x;
 };
```

**Comment by Tarmil** [comment]
I think the problem here is different: you changed the name of the function argument from `x` to `value`, but you didn't change the inline accordingly from `$x` to `$value`, so the semantics are different: `$x` is now just a js variable, not a placeholder for the argument anymore.

Maybe we should look into adding a warning if an inline contains an identifier starting with `$` that is not a function argument.

**Comment by Tarmil** [comment]
If that's ok I'll close this issue and post a new one for the warning.

**Comment by Tarmil** [comment]
Added as #1019.
