### ISSUE TITLE
Parsing number query parameter by server

### ISSUE THREAD

**Issue by V0d01ey** [dotnet-websharper/core#1030]
Consider following code. To the default sample project was added endpoint with query parameter mapping to double value. To the page "About" was added form with number-type input submitting GET request to this endpoint.
```csharp
    public class Server
    {
        <...>
        [EndPoint("GET /send_number")]
        public class SendNumber
        {
            [Query]
            public double number_input;
        }

        [Website]
        public static Sitelet<object> Main =>
            new SiteletBuilder()
                .With<Home>(/*...*/)                
                .With<About>((ctx, action) =>
                    Page(ctx, action, "About",
                        doc(
                            h1("About"),
                            p("This is a template WebSharper client-server application.")
// Form added
                            , form(attr.method("get"), attr.action("send_number"),   
                                input(attr.type("number"), attr.name("number_input"), attr.step("0.1")),
                                button("Send Number")
                            )
                        )
                    )
                )
                .With<SendNumber>((ctx, action) => {
                    return Content.Json(action);
                })
                .Install();
    }
```
If user inputs value "0.1" to form and submit then server gives the page "HTTP Error 404.0 - Not Found" on sent request "http://localhost:57457/send_number?number_input=0.1".
Note that if one changes request parameter to "0,1" then request succeeds.
I think that default number parser should use point as decimal separator as W3C standards (so as Javascript) don't know alternatives to that.

**Comment by Jand42** [comment]
@V0d01ey Thanks for the report, I have done a quick fix to use invariant format in TryParse/ToString for Double/Single in routing.
