### ISSUE TITLE
Microsoft.NET.Sdk.Functions Nuget library can't be connected to Websharper

### ISSUE THREAD

**Issue by AndreiDegtiarev** [dotnet-websharper/core#1036]
After initialization of Microsoft.NET.Sdk.Functions in Visual Studio 2017 via "Managed Nuget Packages" command (project file need to be extended also with command <TargetName="RunResolvePublishAssemblies" />), web page appears with exception.

**Comment by Jand42** [comment]
@AndreiDegtiarev Are you using .NET 4.x or Core? F# or C#?
I have seen that Microsoft.NET.Sdk.Functions have some problems with Newtonsoft.Json dependency versioning that `<Target Name="RunResolvePublishAssemblies" />` fixes but probably there is some assembly loading error during runtime too.

**Comment by AndreiDegtiarev** [comment]
@Jand42 I made following steps:
- In VS2017 new F# Project: Websharper 4 Client-server application with .Net Framework 4.6.1
- Compile, start - everything OK
- Over Manage NuGet Packages I've inserted "Microsoft.NET.Sdk.Functions" (version 1.0.24)
- Project file was extended with <Target Name="RunResolvePublishAssemblies" />
- Compile start - error message in the Edge browser

**Comment by AndreiDegtiarev** [comment]
@Jand42 Sorry, it was my misunderstanding. It makes little sense to connect Microsoft.NET.Sdk.Functions library to Websharper. Actually, my intension was to use Microsoft.WindowsAzure.Storage library.
