### ISSUE TITLE
Badly formatted cookie results in server exception

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1039]
(Initially reported at http://forums.websharper.com/topic/86294)

If a cookie header string does not have a `=`, parsing cookies fails:

https://github.com/dotnet-websharper/core/blob/master/src/sitelets/WebSharper.Sitelets/HttpModule.fs#L109

Previously, before WebSharper added .NET Core support, this relied on `HttpCookieCollection` which is more allowing and could handle badly formatted cookie string, so this is a regression.

**Comment by Tarmil** [comment]
So what should happen in this case? Should we add a cookie with this name and an empty value, or ignore it?

**Comment by Jand42** [comment]
@Tarmil we have to return an interface, so I think it's best to just wrap the underlying HttpCookieCollection and do not enumerate all keys, same as WS.AspNetCore does.

**Comment by Jand42** [comment]
@Tarmil The real question is I realize, why was it converted to use `req.Headers` and handle that by hand instead of `req.Cookies`, do you remember this? Thanks!
