### ISSUE TITLE
WIG: Error running WIG assembly: System.TypeInitializationException

### ISSUE THREAD

**Issue by AlexPeret** [dotnet-websharper/core#1042]
hi,

I've just updated an __extension__ project to WebSharper 4.5.6.320 and it is throwing the following exception:

> FSC: error FS9001: Error running WIG assembly: System.TypeInitializationException: The type initializer for '<StartupCode$WebSharper-FileDropJs>.$Main' threw an exception. ---> System.MissingMethodException: Method not found: 'ClassMembers ClassMembers.NewInstance(Microsoft.FSharp.Collections.FSharpList`1<IClassMember>)'.
> at <StartupCode$WebSharper-FileDropJs>.$Main..cctor()
> 
> --- End of inner exception stack trace ---
> at WebSharper.FileDropJs.Extension.WebSharper-InterfaceGenerator-Pervasives-IExtension-get_Assembly()
> at WebSharper.Compiler.CommandTools.LoadInterfaceGeneratorAssembly(String file)
> at WebSharper.Compiler.CommandTools.RunInterfaceGenerator@322.Invoke(Unit unitVar0)
> et WebSharper.Compiler.AssemblyResolver.Wrap[T](FSharpFunc`2 action)
> at WebSharper.FSharp.Program.Compile@110.Invoke(Unit unitVar0)

This is my environment setup:
- **.NET Version:** .NET Framework 4.7
- **Runtime F# target:** 4.6.0.0
- **FSharp.Core:** v4.6.1
- **WebSharper:** v4.5.6.320

Thanks,
Alex

**Comment by Tarmil** [comment]
Ah, this seems to be an assembly redirect issue in the compiler's App.config. The function expects an FSharpList from FSharp.Core 4.5.0.0, but receives one from FSharp.Core 4.6.0.0 instead. This should be quick to solve, we'll do a quickfix release.

**Comment by Tarmil** [comment]
This is fixed in WebSharper 4.5.7.322.
