### ISSUE TITLE
Potential performance regression in the latest JSON serialization

### ISSUE THREAD

**Issue by nightroman** [dotnet-websharper/core#1057]
Potential performance regression in the latest JSON serialization

Disclaimer: The result are not from a real use case. I was doing some
benchmarking on Json.NET vs. WebSharper and found some performance
regression in the latest release "WebSharper.Core 4.5.12.336".

See the new and old benchmark projects attached.

How to run benchmarks:

- open a project in Visual Studio
- set configuration to Release, hit `Ctrl+F5`
- in the console, when it prompts, type 0 and enter
- wait for the benchmarking results (takes some time)

New results, really worrying with small batches (N - Json.NET, W - WebSharper)

    JsonBench
        <PackageReference Include="WebSharper.Core" Version="4.5.12.336" />

    | Method | ItemCount |         Mean |      Error |     StdDev |
    |------- |---------- |-------------:|-----------:|-----------:|
    |      N |         1 |     3.089 us |  0.0256 us |  0.0227 us |
    |      W |         1 |   732.096 us |  1.8791 us |  1.7577 us |
    |      N |       100 |   236.498 us |  2.5708 us |  2.4047 us |
    |      W |       100 | 1,074.070 us |  8.3925 us |  7.4398 us |
    |      N |      1000 | 2,363.565 us | 10.6541 us |  8.8966 us |
    |      W |      1000 | 5,498.250 us | 61.1580 us | 57.2073 us |

Old results, WebSharper is slower than Json.NET but not that slower

    JsonBenchOld
        <PackageReference Include="WebSharper" Version="4.5.11.334" />

    | Method | ItemCount |         Mean |      Error |     StdDev |
    |------- |---------- |-------------:|-----------:|-----------:|
    |      N |         1 |     3.134 us |  0.0431 us |  0.0403 us |
    |      W |         1 |    10.475 us |  0.0585 us |  0.0547 us |
    |      N |       100 |   240.186 us |  0.5312 us |  0.4969 us |
    |      W |       100 |   366.172 us |  1.3740 us |  1.2180 us |
    |      N |      1000 | 2,357.168 us | 12.3782 us | 10.9729 us |
    |      W |      1000 | 4,414.554 us | 57.1665 us | 53.4736 us |

So the new serialization is somewhat 70x slower for small batches.
This does not look quite right.

[Related change/issue #1056](https://github.com/dotnet-websharper/core/issues/1056)

[Code.zip](https://github.com/dotnet-websharper/core/files/3223860/Code.zip)

**Comment by granicz** [comment]
@nightroman Thanks for checking into this! The new numbers are concerning indeed, need to investigate further.

**Comment by Jand42** [comment]
@nightroman Thank you very much for the catch. I am very sorry, I indeed made a trivial mistake when refactoring: made the expensive initialization of the serializer a static property instead of field. (Conciseness of F# can be a be a bit misleading here with `static member` versus `static let`.)

Fix is coming quick.

**Comment by Jand42** [comment]
@nightroman Pushing to nuget.org right now. (Version `4.5.13.338`)

Performance is weaker compared to Json.NET, bc WS uses a simpler implementation with composing functions instead of Reflection.Emit, so there is space for improvement there but not a trivial rewrite.

**Comment by nightroman** [comment]
All looks good now, thank you.

> Performance is weaker compared to Json.NET...

No problem with that (sorry for this comparison brought to your attention). Json.NET is specifically designed and heavily optimized for this particular task. WebSharper performance is decent and this is quite enough.
