### ISSUE TITLE
Use AsyncLocal instead of ThreadLocal for the remote context

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/core#1061]
https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=netstandard-2.0

This would drop the requirement to retrieve the context before the async block.

**Comment by Jand42** [comment]
@Tarmil Good find, I was not sure AsyncLocal is respected by F# Async workflows but it seems so. The dynamic invoke is also not an issue.
