### ISSUE TITLE
WIG: Namespace not exposing classes

### ISSUE THREAD

**Issue by AlexPeret** [dotnet-websharper/core#1062]
hi!

I've created a WIG extension for Filedrop.js lib, which used to work in previous version of WebSharper (4.5.15.342).

After updating to version 4.5.16.344, the main class **FileDrop** is not visible anymore.

You can find the extension at https://github.com/AlexPeret/WebSharper.FileDrop.js, with an incomplete sample project for testing.

_By the way, the project is not mature, althought it is working on a private project, but if you find it useful and want to incorporate into your repository, feel free to do it. And let me know if I'm using the wrong license._

Best regards,
Alex

**Comment by Jand42** [comment]
@AlexPeret Hi, I think you should just restart Visual Studio, or maybe a clean and rebuild. WebSharper uses .targets file to modify the compiler tool path, and VS might not pick the change up well on a nuget update without a restart.

I get no errors on `FileDrop` in your sample project (only on some unfinished code in `PageSamples.fs`)

**Comment by AlexPeret** [comment]
thank you András!

Update-Package -reinstall followed by restart and clean solution fixed it.

I'm closing the ticket.

Thanks!
