### ISSUE TITLE
Javascript Inline Parser -> "import" function changed, which does not work in browser

### ISSUE THREAD

**Issue by asiye1** [dotnet-websharper/core#1070]
`    [<Inline """
        {
        var sc = import('./pkg/scenariolib.js');
        console.log(sc);
        return sc;
        }
    """>]` 

is parsed to 

`  {
   var r,sc;
   sc=Global["import"]("./pkg/scenariolib.js");
   console.log(sc);
   r=sc;
   console.log(r);
  },` 

which does not run in the browser (Error: Uncaught TypeError: Global.import is not a function).

If import is not working, is there another way to import ES6 modules?

Websharper V 4.5.15.342

**Comment by Jand42** [comment]
WS does not recognize `import` as a keyword yet, yes, this could be added quickly that your example works as intended. Marking this for next release, soon.

**Comment by Jand42** [comment]
Currently, `import` is handled as a reserved word, that's why WS wants to reach it through the `Global` object (an alias of `window`). It is good to keep there, so WS does not generates a variable named import from C#/F# code, but adding an extra case to inline string recognizer to parse it as the import keyword function.

**Comment by asiye1** [comment]
Thank you for the fast reply! That's great having the 'import' function in the next version! For now, I have found a workaround, but will definitely return to the 'import' in Inline after it is added.

**Comment by asiye1** [comment]
(The workaround is not really a best practice..)

**Comment by Jand42** [comment]
@asiye1 Hi, JS import features are out now in https://github.com/dotnet-websharper/core/releases/tag/4.7.0.423
