### ISSUE TITLE
Ambiguity at translating trait call

### ISSUE THREAD

**Issue by amieres** [dotnet-websharper/core#1074]
So this code works in F#

    type  Val<'P> = VView of View<'P> | VConst of 'P
        with
        [<Inline>] static member ( <* )(vf:Val<'a->'b> , a :    'a ) = VConst a
        [<Inline>] static member ( <* )(vf:Val<'a->'b> , aV:Var<'a>) = VView  aV.View

    let add1 a = a + 1
    let a11V = Var.Create 11

    let mainX = VConst add1 <* a11V

but WebSharper gives the following error:

    WebSharper error FS9001: Ambiguity at translating trait call: op_LessMultiply; Could not find method for trait call: op_LessMultiply; types: Val`1<(System.Int32 -> System.Int32)>, WebSharper.UI.Var`1<System.Int32>

**Comment by Jand42** [comment]
@amieres Thanks for the report! FSC does not help much in disambiguating trait calls/operator overloads the last time I checked, so WS tries to replicate the type inference, but seems that it is not sufficiently recursive enough to eliminate the first of your definitions.
Code in question: https://github.com/dotnet-websharper/core/blob/master/src/compiler/WebSharper.Compiler/Translator.fs#L1033-L1052
I will take a look and use your scenario as test case.

**Comment by amieres** [comment]
Excellent! thanks for checking it.

**Comment by amieres** [comment]
I see the problem, each parameter (and return type) gets tested for generic compatibility independent of  the other, so it does not take into account when generics are shared. I believe the same thing happens in the method `IsGenericCompatible`.

**Comment by Jand42** [comment]
Fix released in https://github.com/dotnet-websharper/core/releases/tag/4.6.0.361
