### ISSUE TITLE
Map constructor error when the seq has duplicate keys

### ISSUE THREAD

**Issue by FilippoPolo** [dotnet-websharper/core#1094]
Hi all,

There's a problem with the Map constructor that happens when the seq parameter contains multiple elements with the same key (but differing value). In .NET, this results in a Map containing the last seq value for a given key; in W#, this results in a Map containing the first seq value for a given key.

Repro:

```
let test() =
    let listWithDupes=[("A",1);("B",2);("A",3)]
    let m = Map listWithDupes
    let i = m.Item("A")
    // This is 3 on .NET, and 1 in W#.
    i
```

Tested on 4.6.1.381.

**Comment by Jand42** [comment]
@FilippoPolo Thanks, good catch, indeed WS Proxy uses Seq.distinctby, which keeps first value https://github.com/dotnet-websharper/core/blob/master/src/stdlib/WebSharper.Collections/Map.fs#L36
I am adding a `rev` there, maybe optimizing a bit.
