### ISSUE TITLE
Need ability to explictly exclude a resource

### ISSUE THREAD

**Issue by endeavour** [dotnet-websharper/core#1097]
In my scenario I am using WebSharper.Forms.BootStrap. Because of this it websharper automatically inserts a <link> tag to include bootstrap.min.css from the bootstrap CDN.

This causes problems if I want to use my own custom CSS file with colour/theme tweaks for example. It would be nice to be able to tell websharper to explictly ignore certain resources (both CSS and JS).

**Comment by ArtemyB** [comment]
@endeavour I'm agree with you, ability to ignore the resource could be useful. However there is already a way to override predefined resource files. The details you can find in the section "JavaScript → Resources→ Overriding Resource URLs": https://developers.websharper.com/docs/v4.x/fs/resources#heading-8. I suppose using this feature you can emulate a complete exclusion of some resource by replacing its file with your own empty file for example.

**Comment by Jand42** [comment]
@endeavour @ArtemyB I have tested, having this in `web.config`

```xml
  <appSettings>
    <add key="WebSharper.Forms.Bootstrap.Resources.CSS" value="" />
  </appSettings>
```
or this in `appsettings.json` (for .NET Core)
```json
    "websharper": {
        "WebSharper.Forms.Bootstrap.Resources.CSS": ""
    }
```
then WebSharper still creates the `link` tag fort it but with an empty `href` which browsers should ignore but its also unnecessary. So this solution works, but I will remove printing this link at all.
