### ISSUE TITLE
Impossible to load assemblies for SwaggerProvider.DesignTime.dll (SwaggerProvider)

### ISSUE THREAD

**Issue by vrescobar** [dotnet-websharper/core#1099]
Hello,

if I create the websharper mvu project with F# and I try to add the SwaggerProvider the project cannot compile anymore even if I am not opening the module or using any feature.

This project should be 100% compatible in server side and I was aiming to use it on the client side as well but I didn't get that far.

## Steps to reproduce

1. Create a new WS template (F#)
2. Add `<PackageReference Include="SwaggerProvider" Version="0.10.2" />`
3. Try to compile
4. If it didn't crash yet add the hello world snippet from its [docs](http://fsprojects.github.io/SwaggerProvider/#/)

## The error

`Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'SwaggerProvider.DesignTime.dll' which cannot be loaded or doesn't exist. Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

Note that `SwaggerProvider.DesignTime.dll` does indeed exists and works perfectly on other netcoreapp3.1 projects.

## What was supposed to happen

It was supposed to be one of the most incredible features from F# available in client and server side, no need to have js client libraries anymore, etc Fable doesn't have this feature yet, so I was aiming for websharper to transpile it on the client side.

**Comment by granicz** [comment]
I am pretty sure this is a general TP issue with non-framework targets, rooted with the F# TP SDK. Can you try with targeting NET4x (use the .NET framework templates for WebSharper from the VSIX installer - this only works with VS, not VSC unfortunately.)

**Comment by vrescobar** [comment]
I was using JetBrains Rider btw. And the TP was working well in other projects.

Which template would you recommend? Could you point me to the exact place where I could fetch it?

**Comment by granicz** [comment]
On a second thought, we should check into this indeed.

Re the template, I'd try the SPA or the Client-Server one, but be sure to target .NET4x. You can grab the VSIX installer from http://websharper.com/downloads by clicking the big blue button under the "Using Visual Studio" section.

**Comment by vrescobar** [comment]
I couldn’t ind how to install VSIX extensions, and apparently it is just not possible at visual studio for mac. 
https://developercommunity.visualstudio.com/content/problem/67655/cant-install-vsix-to-vs-for-mac.html <https://developercommunity.visualstudio.com/content/problem/67655/cant-install-vsix-to-vs-for-mac.html>

If you know anyway to install the template at VS for mac let me know.

**Comment by vrescobar** [comment]
Additionally for mac we've only got the 2.1 and 3.1 versions supported (and a preview of the 5.0)

https://dotnet.microsoft.com/download/dotnet-core

**Comment by granicz** [comment]
OK, remember, here we are trying to test your scenario on .NET4x and not on .NET Core. I can always just send a .NET4x-targeted empty WS project as a ZIP, but if you are trying to edit it with VS for Mac, I don't know if it will work. Worth a try, here you go:
[EmptyClientServer.zip](https://github.com/dotnet-websharper/core/files/4580055/EmptyClientServer.zip)

**Comment by granicz** [comment]
FWIW, there is some chat on the WebSharper gitter that this issue might not be TP-related after all. Please join and chip in with your insights, it's at https://gitter.im/intellifactory/websharper

**Comment by vrescobar** [comment]
As you say I cannot test the one compatible with mac (netstandard3.1) which also has already the bug I reported. We can try to speak in the chat.

**Comment by granicz** [comment]
@Jand42 will now try this with the latest fixes, hopefully it should just work now.

**Comment by mrtank** [comment]
With the .NET 5.0 version it was possible to import the SwaggerProvider nuget package and use it. Thanks @Jooseppi12 for testing.
```fsharp
let [<Literal>] Schema = "https://petstore.swagger.io/v2/swagger.json"
type PetStore = OpenApiClientProvider<Schema>
...
let AboutPage ctx =
        let client = PetStore.Client()
        async {
            let! inv = client.GetInventory() |> Async.AwaitTask
            return!
                Content.Page(
                    Templates.MainTemplate()
                        .Title("About")
                        .MenuBar(Templating.MenuBar ctx About)
                        .Body(
                            [
                                 h1 [] [text "About"]
                                 p [] [text "This is a template WebSharper client-server application."]
                                 div [] [
                                     yield!
                                        inv
                                        |> Map.toList
                                        |> List.map (fun (k, v) ->
                                            p [] [text <| sprintf "%s - %d" k v]
                                        )
                                 ]
                            ]
                        )
                        .Doc()
                )
        }
```
![image](https://user-images.githubusercontent.com/918230/132673250-26e9530d-2149-47b9-b246-2d41e344588f.png)
