### ISSUE TITLE
Content.Text adds invisible whitespace to output

### ISSUE THREAD

**Issue by panesofglass** [dotnet-websharper/core#1105]
The tests for https://github.com/the-benchmarker/web-frameworks/pull/2888 are [failing](https://travis-ci.com/github/the-benchmarker/web-frameworks/jobs/346510190). When printed out, they look correct, e.g. `"" = ""` or `"0" = "0"`. However, there is evidence of additional characters or at least mismatched encoding. According to the project, encoding should be UTF-8, which should match `Content.Text`'s output. However, something is clearly added that doesn't appear to affect normal parsing or processing.

**Comment by Tarmil** [comment]
Alternately, this should be equivalent: `Content.Text msg |> Content.WithContentType "text/plain"`

**Comment by panesofglass** [comment]
Strangely, the above results in the same issue. In Postman, I'm able to download the the response, even though when I open the file it appears empty. However, with the following, I get a true, empty body:

``` fsharp
let Text (msg: string) =
    Content.Custom(
        WriteBody = fun s ->
            let bytes = System.Text.Encoding.UTF8.GetBytes(msg)
            s.Write(bytes, 0, bytes.Length))
```

**Comment by granicz** [comment]
You mentioned extra characters - can you paste a screenshot of the difference between the two functions above?

**Comment by panesofglass** [comment]
I deleted the file I downloaded from Postman. It's some sort of non-printing whitespace character. I cannot comprehend why the `StreamWriter` would add it.

@Tarmil's:
``` fsharp
let Text (msg: string) =
    Content.Custom(
        Headers = [Http.Header.Custom "content-type" "text/plain"],
        WriteBody = fun s ->
            let encoding = System.Text.Encoding.UTF8
            use w = new System.IO.StreamWriter(s, encoding)
            w.Write msg
    )
```

Mine:
``` fsharp
let Text (msg: string) =
    Content.Custom(
        WriteBody = fun s ->
            let bytes = System.Text.Encoding.UTF8.GetBytes(msg)
            s.Write(bytes, 0, bytes.Length)
    )
```

The only differences are that I get the bytes and write them directly, whereas the original uses a `StreamWriter` to write to the stream.

**Comment by Tarmil** [comment]
It looks like `StreamWriter` actually writes the 3-byte UTF-8 byte order mark `EF BB BF`. It would be a better fix to prevent it from doing that, rather than use `GetBytes` which creates an intermediary byte array. [The trick](https://stackoverflow.com/a/11655096/762363) is to use `new UTF8Encoding(false)` instead of the static `Encoding.UTF8`. I can confirm that the following writes 0 bytes:

```fsharp
let defaultEncoding = new System.Text.Encoding.UTF8Encoding(false)

let Text (msg: string) =
    Content.Custom(
        WriteBody = fun s ->
            use w = new System.IO.StreamWriter(s, defaultEncoding)
            w.Write(msg)
    )
```

**Comment by panesofglass** [comment]
Awesome! I didn’t know about that!

**Comment by panesofglass** [comment]
As Content.Text already accepts an encoding parameter, it seems this is not a bug. Should I just close this?
