### ISSUE TITLE
System.Decimal implementation incomplete

### ISSUE THREAD

**Issue by Arithmomaniac** [dotnet-websharper/core#1109]
Using WebSharper.MathJS.Extensions 4.6.7.408, `decimal.Floor`, `decimal.Ceiling`, and The '>' operator were missing. There may be more, I didn't check.

**Comment by granicz** [comment]
FYI, here is the [source](https://github.com/dotnet-websharper/core/blob/master/src/stdlib/WebSharper.MathJS.Extensions/Decimal.fs) (and check one folder up too for direct MathJS code) - in case you want to take a stab at adding missing features.

Also, there is a pretty slim doc page around symbolic math [here](https://developers.websharper.com/docs/v4.x/fs/math).

**Comment by Jand42** [comment]
Released now in https://github.com/dotnet-websharper/core/releases/tag/4.7.3.446
Thanks to @btamas2000
