### ISSUE TITLE
Update to FCS 40 and F# 5

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1112]
F# 5 features to test on .NET 5.0: (See [announcement](https://devblogs.microsoft.com/dotnet/announcing-f-5/))

- [x] String interpolation
- [x] `nameof`
- [x] Enhanced slicing
- [x] Applicative Computation Expressions 
- [x] Default interface member consumption
- [x] Implicit interop with nullable value types

**Comment by mrtank** [comment]
Even FCS 40.0

**Comment by granicz** [comment]
Need test case coverage for each of the above.

**Comment by granicz** [comment]
@btamas2000 If you need help with the extra test coverage, ping here, thanks!

**Comment by btamas2000** [comment]
String interpolation, `nameof`, slicing in 3fa7267d4699530bdbdf3efb48016aec72564201

**Comment by Jand42** [comment]
WebSharper 5.0 is now updated to FCS 40.0, in #1142

**Comment by btamas2000** [comment]
`Applicative Computation Expressions` in https://github.com/dotnet-websharper/core/commit/1ec359281aad4fa511412d9773e18a15a582870f

**Comment by btamas2000** [comment]
For future reference, in the PR the test for `Default interface member consumption` is added but as comment, so when this feature becomes available in F# the test can be easily added.

**Comment by Jand42** [comment]
Only default interface member consumption is not working yet, as that requires a C# feature, track at #1049
