### ISSUE TITLE
WIG Pattern.OptionalFields accessing wrong property

### ISSUE THREAD

**Issue by dvdkon** [dotnet-websharper/core#1115]
When a property is generated by `Pattern.OptionalFields`, accessing the "...Opt" variant should translate to accessing the base-name property in JavaScript. Due to a bug, the resulting JS code accesses the non-existent "...Opt" property.

Sample WIG F# code:
```fsharp
let C1 =
    Class "C1"
    |+> Pattern.OptionalFields [
        "field", T<int>
    ]
```

Resultant .DLL decompiled to C#:
```csharp
public class C1 {
	public Optional<int> FieldOpt {
		[Inline("$this.fieldOpt")]
		get {
			throw new NotImplementedException();
		}
		[Inline("$wsruntime.SetOrDelete($this, 'fieldOpt', $value)")]
		set {
			throw new NotImplementedException();
		}
	}

	public int Field {
		[Inline("void ($this.field = $value)")]
		set {
			throw new NotImplementedException();
		}
	}
}
```

Note how the `Inline` annotation contains `fieldOpt`, when it should contain just `field`.

I tried to fix this myself, but I couldn't get WebSharper to build. All it should take as far as I know is `WithSourceName` in [the function](https://github.com/dotnet-websharper/core/blob/5e15736178967fda5123b455c827150753c132cf/src/compiler/WebSharper.InterfaceGenerator/Pattern.fs#L61).

**Comment by granicz** [comment]
@dvdkon Thanks for the report! First and foremost is to figure out why the repo wouldn't build for you. Could you post the error you are seeing on a separate ticket? Thanks!

**Comment by dvdkon** [comment]
All right, here's the issue number: #1118

**Comment by Jand42** [comment]
@dvdkon Thanks for the report, fix will be in next release soon.
Workaround: 
Define `OptionalFields` helper for yourself, it's just a convenience tool built upon other public WIG API operators and functions.

```fsharp
    let OptionalFields (optional: seq<string * Type.Type>) =
        Instance [
            for (n, t) in optional do
                yield n =! t :> _
                let sn =
                    let name = n.Replace('.', '_')
                    name.Substring(0, 1).ToUpper() + name.Substring 1 + "Opt"
                yield n =@ !?t |> WithSourceName sn :> _
        ]
```

**Comment by Jand42** [comment]
@dvdkon Fix is part of https://github.com/dotnet-websharper/core/releases/tag/4.7.0.423
