### ISSUE TITLE
Errors building with ./build.sh

### ISSUE THREAD

**Issue by dvdkon** [dotnet-websharper/core#1118]
I'm trying to build this repository  
**OS**: Arch Linux (latest packages)  
**.NET Core**: 3.1.404  
**Mono**: 6.10.0  

Running `./build.sh` fails with
```
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
```

Replacing `dotnet restore` in `build.sh` with
```
dotnet restore WebSharper.sln
dotnet restore WebSharper.Compiler.sln
```
fixes this particular issue.

With the fix the build fails with
```
GetReferenceAssemblyPaths: /usr/share/dotnet/sdk/3.1.404/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
Fsc: /usr/share/dotnet/sdk/3.1.404/FSharp/Microsoft.FSharp.Targets(279,9): error MSB6006: "wsfsc.sh" exited with code 1.
```
[Full log](https://github.com/dotnet-websharper/core/files/5574500/buildlog2.txt)

Exporting `FrameworkPathOverride=/usr/lib/mono/4.6.1-api` as suggested on [StackOverflow](https://stackoverflow.com/a/55070707) got rid of that error, but `wsfsc.sh` still fails without any indication as to why:
```
Fsc: /usr/share/dotnet/sdk/3.1.404/FSharp/Microsoft.FSharp.Targets(279,9): error MSB6006: "wsfsc.sh" exited with code 1.
```
[Full log](https://github.com/dotnet-websharper/core/files/5574550/buildlog3.txt)

**Comment by Jand42** [comment]
@dvdkon Thanks for the report, I have switched to using dotnet cli tool for Paket/FAKE, updated build.sh too to restore everything properly.
