### ISSUE TITLE
Build errors on .net SDK 5.0.200 (only F#)

### ISSUE THREAD

**Issue by nighby** [dotnet-websharper/core#1123]
Build fails on latest .net SDK with the following obscure error message:

    "FSC : WebSharper error FS9001: You must provide assembly output path."

Appears to be F# specific, omitting `-lang F#` from below steps allows build.

#### Steps to reproduce

    $ dotnet new websharper-web -lang F#
    $ dotnet build

#### Generated project file
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Remoting.fs" />
    <Compile Include="Client.fs" />
    <Compile Include="Site.fs" />
    <Compile Include="Startup.fs" />
    <Content Include="Main.html" CopyToPublishDirectory="Always" />
    <None Include="wsconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WebSharper" Version="4.7.0.423" />
    <PackageReference Include="WebSharper.FSharp" Version="4.7.0.423" />
    <PackageReference Include="WebSharper.UI" Version="4.7.0.231" />
    <PackageReference Include="WebSharper.AspNetCore" Version="4.7.0.157" />
  </ItemGroup>

</Project>
```

#### Environment
Debian 10
.NET SDK (reflecting any global.json):
 Version:   5.0.200, 
 Commit:    70b3e65d53

**Comment by nighby** [comment]
Websharper command that is being run, we can clearly see the `-o` being passed in which maps to [AssemblyFile](https://github.com/dotnet-websharper/core/blob/master/src/compiler/WebSharper.FSharp/Program.fs#L358):
```
/home/nighby/.nuget/packages/websharper.fsharp/4.7.0.423/build//../tools/netcoreapp3.1/wsfsc.sh "/usr/share/dotnet/sdk/5.0.200/FSharp/fsc.dll" -o:obj/Debug/netcoreapp3.1/test.dll
-g
--debug:portable
... rest of arguments
```

**Comment by nighby** [comment]
Workaround: sudo apt-get install dotnet-sdk-5.0=5.0.103-1

**Comment by nighby** [comment]
I have a feeling this is due to 5.0.200 using fsc.dll (/usr/share/dotnet/sdk/5.0.200/FSharp/fsc.dll), and 5.0.103 using fsc.exe (/usr/share/dotnet/sdk/5.0.103/FSharp/fsc.exe) in conjunction with https://github.com/dotnet-websharper/core/blob/master/src/compiler/WebSharper.FSharp/Program.fs#L316, it is probably throwing out the arg parser ordering

**Comment by Jand42** [comment]
@nighby I have pushed a global.json update on master to use 3.1 SDK only while I am focusing on websharper50 branch to finish full support for .NET5/F#5/C#9.

**Comment by granicz** [comment]
@Jand42 Any news on this? We need this released ASAP.

**Comment by catfly1** [comment]
FWIW, I tried to use `5.0.0.9-preview1` via https://daily.websharper.com/nuget which appears to be the latest preview, and it does not yet seem fixed, though source on this repos websharper50 branch indicates it is (i dont see an obvious mapping between this repo and daily.websharper.com).

**Comment by Jand42** [comment]
@nighby @granicz @catfly1 Fix released in https://github.com/dotnet-websharper/core/releases/tag/4.7.1.432
