### ISSUE TITLE
FS3186 warning after upgrade to .net 5 (v5.0.3) (SDK 5.0.200 ASP.NET Core Runtime 5.0.3)

### ISSUE THREAD

**Issue by ingted** [dotnet-websharper/core#1124]
unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 1 in table 'itycons' of assembly 'WebSharper.Core.JavaScript, Version=4.7.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.

All the code were not changed (just upgrade .net 5 from 5.0.0 to 5.0.3)... and unable to identify which part triggers this warning.

**Comment by Jand42** [comment]
@ingted This has been a benign warning from FSharp.Compiler.Services for a while... Full .NET5/F#5/C#9 support is coming soon, currently on websharper50 branch, it might solve it by using a newer FSharp.Compiler.Services
