### ISSUE TITLE
Investigate stress testing issues

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1139]
WebSharper on ASP.NET Core can become completely blocked up during stress testing and failing. Investigate.

**Comment by granicz** [comment]
Re your first commit, it makes no sense to create a default that yields suboptimal performance - who would ever want that?

**Comment by granicz** [comment]
Also, please add more details on the nature of requests. Last I checked, WebSharper throughput for simple requests (empty to empty page) was in the tens of thousands per second. So if performance degrades, those request likely involve request parsing and async response generation, so I'd look there first.

**Comment by Jand42** [comment]
@granicz Commit https://github.com/dotnet-websharper/aspnetcore/commit/195cbd23e731bb8657105ad4434eb69e217f6408 seems to be resolving the issue, having the `syncIOFeature.AllowSynchronousIO <- true` hack was the main suspect, and indeed it seems so, verified with load testing. This hack was added bc ASP.NET Core 3.1 would fail otherwise and this was the quickest way to resolve that.

Changes in WebSharper and WS.UI were added to have them not close the output stream when disposing the TextWriter. This allows WS.ANC to pass in a MemoryStream that WS.Sitelets can write synchronously (as all asynchronous Sitelet/Page processing is done at this point), and copy the result asynchronously to the ANC response stream.

I have added a configurable static variable `AutoFlushPageWriter` in `WebSharper.Sitelets.Content`, so that ANC can turn off AutoFlush on the TextWriter used when writing Page content, gaining some performance. I have kept it on by default thinking that I might break streamed response writing, but I realize now that actually streamed response is only doable in WS if you are using CustomContent yourself and asynchronous writing is not supported bc WriteBody is syncronous. So proper asynchronous streamed response will need bigger API changes anyways, so I can remove this unnecessary bool flag indeed.

**Comment by Jand42** [comment]
`leaveOpen=true` was also added in UI templating response writer: https://github.com/dotnet-websharper/ui/commit/97fc893ea2f87036e2aac3547b3067a06b0cb310

And the main change is here in WebSharper.AspNetCore, do not use AllowSynchronousIO hack, but write to a MemoryStream synchronously then copy to response stream asynchronously: https://github.com/dotnet-websharper/aspnetcore/commit/195cbd23e731bb8657105ad4434eb69e217f6408
