### ISSUE TITLE
Update F# Map/Set RPC encoder/decoder for FSharp.Core 5.0

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1143]
Internals of FSharpMap/Set has changed with FSharp.Core 5.0, the tree is no longer represented by F# unions but classes. This breaks WebSharper's RPC decoder/encoder which relies on these internals.

Update for FSharp.Core 5.0 for WebSharper 5.0 release.

**Comment by granicz** [comment]
If the encoding format is changing, please add a detailed description with samples depicting what it will become.

**Comment by Jand42** [comment]
@granicz Nothing's changing from the outside as part of this ticket - this is just to adjust WebSharper's RPC encoding/decoding internals to FSharp.Core 5.0's internals.

**Comment by Jand42** [comment]
Resolved for FSharp.Core 5.0 in WebSharper 5.0-preview
