### ISSUE TITLE
For WebSharper 5, run Chutzpah testing without IIS

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1144]
Remove PublishTests and modify RunTests buils steps, no more need to deploy into IIS, just start process with dotnet run, run the tests, then stop the process.

**Comment by mrtank** [comment]
The step should improve on `dotnet` tooling integration. So instead of start process with `dotnet run`, run tests, stop process, it should just run `dotnet test`. Reporting passed/failed tests. Possibly better integration with test tools (coverage, collect, etc.)

**Comment by mrtank** [comment]
https://matthewmanela.com/blog/chutzpah-4-3-0-web-server-mode/ might help us deploy to Kestrel.

**Comment by mrtank** [comment]
Instead of Chutchpah, which is net4x only we are considering using phantomjs.exe + qunit-phantomjs-runner.

**Comment by Jand42** [comment]
Running tests with Kestrel in def85e39b75b58457f23355125a29c5260e74a6d
