### ISSUE TITLE
Decimal Error

### ISSUE THREAD

**Issue by ingted** [dotnet-websharper/core#1148]
When using VS2019 creating an **brand new** Websharper Client-Server project and adding the following code into client,

```
let x = 0m + 0m
```

the project will unable to build. And got compilation error:

```
WebSharper error FS9001: Could not find method for trait call: op_Addition targets: source:((System.Decimal * System.Decimal) -> System.Decimal); Could not find method for trait call: op_Addition targets: source:((System.Decimal * System.Decimal) -> System.Decimal); types: System.Decimal, System.Decimal
```

![image](https://user-images.githubusercontent.com/4289161/124384858-d00cb200-dd05-11eb-81b9-1f0e115982b6.png)

![image](https://user-images.githubusercontent.com/4289161/124384870-e0249180-dd05-11eb-8bb5-0d520f8570b9.png)

**Comment by ingted** [comment]
And if I don't add let x = 0m + 0m in client,
The deserialization of decimal would failed here:

![image](https://user-images.githubusercontent.com/4289161/124385079-d6e7f480-dd06-11eb-8e3e-f58421dccd97.png)

in WebSharper.Main.js

The error message is like tihs:

![image](https://user-images.githubusercontent.com/4289161/124385111-01d24880-dd07-11eb-92a6-d79291303b33.png)

**Comment by ingted** [comment]
BTW, seems like a System.DateTime object would be serialized to an integer... not a datetime object in javascript

**Comment by granicz** [comment]
This seems like a bug, but - can you try adding a reference to `WebSharper.MathJS`?

**Comment by ingted** [comment]
Let me try it!!

**Comment by ingted** [comment]
![image](https://user-images.githubusercontent.com/4289161/124404433-7c35b380-dd6d-11eb-9a02-9f0f3fe5ddbc.png)

Really COOL!!! 

Thanks so much!! Now it works!!

Should I close this issue?

**Comment by Jand42** [comment]
@ingted I have created a ticket back then to recognize missing proxies that are in WS.MathJS and give specific error messages on them to advice adding package reference, but it was not prioritized, but we could get around to this: #196 
Or feel free to ask for assistance if you feel like doing a PR for WebSharper and run into any blockers. :) Even though WebSharper 5.0 is in the works, these useful additions to master are still welcome and will be ported over.

**Comment by ingted** [comment]
Hi @Jand42 ,  I think WebSharper.MathJs is wonderful for me so far...
I will wait the 5.0 release^^

**Comment by Jand42** [comment]
Updated MathJS bindings and support for decimal Floor/Ceiling methods are now released in https://github.com/dotnet-websharper/core/releases/tag/4.7.3.446
Also in WebSharper 5.0 preview builds, closing this.
