### ISSUE TITLE
WIG project dll file reference

### ISSUE THREAD

**Issue by ingted** [dotnet-websharper/core#1149]
Excuse me, 

I found that if I want to use my customized WIG project, I must and must not to do:

1. Must to rename the dll file, or F# project will not recognize the WIG class defined like 
```
    let echarts =
        Class "echarts"
        |+> Static [
```
2. Must not DIRECTLY reference WIG project in websharper project (dll path reference required), or the namespace will only having Extension class...

Are these by designed?

**Comment by Jand42** [comment]
@ingted WIG is a bit tricky in it's compile behavior, it first builds as a normal .dll from the code you wrote, then WebSharper compiler invokes this code to generate your assembly definition object, and based on this write a final dll.

If in VS/VSCode you have multi-project checking turned on, things indeed seem broken, as the language service does not know about this discrepancy of your code and final dll output. So working with WIG projects, to have code service work nicely, you must either 
* turn off "Enable in-memory cross project references" in VS (found no such workaround for VSCode+Ionide-fsharp...)
* indeed, reference the output dll directly, you should also set up a project dependency in sln for correct build order

Also, for .NET Standard WIG projects, you need `<PackageReference Update="FSharp.Core" Version="4.7.2" />` at the moment, WebSharper 5.0 is coming soon with proper FSharp.Core 5.0 and .NET 5 support.

**Comment by ingted** [comment]
Thank you so much!!! Now I got it!! 
I love WebSharper so much.... it is GREAT product.
