### ISSUE TITLE
Include the compiler version in the Booster's title

### ISSUE THREAD

**Issue by granicz** [dotnet-websharper/core#1156]
Currently, Task Manager shows `wsfscservice.exe` - it would be a whole lot more helpful if it said "WebSharper Booster 5.0.0.50".

**Comment by granicz** [comment]
So we don't want to change the filename, but we can change the title and/or description to include the above info.

**Comment by Jand42** [comment]
Should be resolved by setting the AssemblyTitle attribute. Maybe via MsBuild, or generate a file with build.fsx to include from within the ./build folder.
