### ISSUE TITLE
Separate WebSharper.JQuery into its own nuget package

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1160]
We don't need it for any main functionality any more, could be split off for WebSharper 5.0. (Keep for WS4.7, as this is a breaking change, needs consumers to add package reference to WebSharper.JQuery if they are using it)

**Comment by granicz** [comment]
(Just for the record, jQuery was only used as a dependency in those legacy pre-5.0 projects that explicitly required `WebSharper.JQuery` as a NuGet package, even though this package was sourced from this core repository.)

**Comment by Jooseppi12** [comment]
Closed as #1174 got merged

**Comment by mrtank** [comment]
https://github.com/dotnet-websharper/jquery is the separate repo
