### ISSUE TITLE
Replace `AjaxWith` with a similar `XMLHttpRequest` solution (WS5)

### ISSUE THREAD

**Issue by btamas2000** [dotnet-websharper/core#1172]
Since JQuery gets taken out from Core, provide a method similar to `AjaxWith` in `WebSharper.Sitelets.Router` (also change `Ajax` method).

Should be based on `XMLHttpRequest` (MDN: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest)

**Comment by Jooseppi12** [comment]
Closed as #1174 got merged
