### ISSUE TITLE
`XMLHttpRequest.send()` binding is incorrect

### ISSUE THREAD

**Issue by btamas2000** [dotnet-websharper/core#1173]
Current binding (in https://github.com/dotnet-websharper/core/blob/master/src/stdlib/WebSharper.JavaScript/Html5.fs ) is
```fsharp
...
    "send" => !?Dom.Interfaces.Document?body ^-> T<unit>
...
```
`XMLHttpRequest.send()` documentation: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send

**Comment by Jooseppi12** [comment]
Closed as #1174 got merged
