### ISSUE TITLE
Add missing C# friendly overload for Application.Text

### ISSUE THREAD

**Issue by Jooseppi12** [dotnet-websharper/core#1176]
Application.SinglePage and Application.MultiPage has it's C# friendly overload, but Application.Text is missing that.

**Comment by Jooseppi12** [comment]
Closed as the code changes are merged to websharper50 branch

**Comment by btamas2000** [comment]
Reopened as earlier solution turned out to be incorrect

**Comment by btamas2000** [comment]
Closed as solution is merged
