### ISSUE TITLE
Projects referencing sitlets.target fail to build

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/core#119]
Error:
`[C:\Windows\Microsoft.Net\assembly\GAC_MSIL\FSharp.Compiler\v4.0_4.3.0.0__b03f5f7f11d50a3a\FSharp.Compiler.dll] A valid typedef or typeref token is expected to follow a ELEMENT_TYPE_CLASS or ELEMENT_TYPE_VALUETYPE. [c:\projects\Website7\Website7\Website\Website.fsproj]`

Attachments: output of msbuild.exe from visual studio and command line for the Sample Web Application template (VS2012). The same problem exists for all templates referencing `"$(WEBSHARPER_HOME)/IntelliFactory.WebSharper.Sitelets.targets"` in vs2012 and vs2010 (couldn't test with vs2008). 

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/119
- Originally reported by: Anonymous
- Originally created at: 2013-04-04T21:58:03.650

**Comment by Tarmil** [comment]
Outdated 2.x issue.
