### ISSUE TITLE
Get rid of static metadata loading in WebSharper.Web.Shared

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1197]
Deserialize WebSharper metadata during ASP.NET Core configuration, using dependency injection if needed.

This will make WebSharped sitelets more flexible for testing.

**Comment by granicz** [comment]
@Jand42 Can you elaborate on plans here?

**Comment by Jand42** [comment]
WebSharper.AspNetCore API changes:

* added `.SiteletAssembly(asm)` method on `WebSharperBuilder` (to be used inside `.UseWebSharper` call in `Startup.Configure`). Sets the assembly used for getting sitelets runtime metadata, this is not needed in web projects themselves (defaults to entry assembly), but can be used for testing, to select which assembly is the WS web project (and thus contains the sitelet runtime metadata). All referenced assemblies are not force-loaded and discovered for an assembly-level `Sitelet` attribute any more if a Sitelet object is not provided, but only the SiteletAssembly (again, the entry assembly by default).
* added `.Metadata(meta)` method on `WebSharperBuilder`. This a cover-all when you want to override WebSharper's metadata for any reason, but generally not needed. Defaults to reading runtime metadata from SiteletAssembly.

Module level static metadata loading in `WebSharper.Web.Shared` has been removed.
