### ISSUE TITLE
Add more build targets for modular local builds

### ISSUE THREAD

**Issue by granicz** [dotnet-websharper/core#1228]
- [x] Move creating OS/platform-specific executables as part of a new `publish` target
- [x] Move compiler/all tests into a new `tests/allTests` target
- [x] Move building extensions/stdlib into a new `buildAll` target

The default `build` target should simply compile the compiler.

**Comment by Jand42** [comment]
@granicz For all, default would be Release mode, with an optional `-d/--debug` flag for Debug mode build.

A good addition to the `publish` step is another flag to determine runtime(s): `--rid:win,linux,linuxmusl,macos`.
Ideally, on GHA, a matrix build would build, test and package it all for all platforms, and there would be a new target CombinePackages for CI purposes that creates final nuget with all platform-specific builds.

This way a single local full fuild is not running multiple runtime publishers but we have optimized compiler for all main platforms and a fallback, all packaged in one.

**Comment by granicz** [comment]
We are looking for a fast turnaround on this, dissecting what we have and exposing it via different build options. We can contemplate on enhancements such as GHA matrix builds in a separate ticket.

Remember the basics: people should be able to make an incremental builds (and that doesn't mean NuGet packages) with simple build parameters with a compiler/proxy/stdlib fix/addition without unnecessary overhead. They should be able to create a new test project, reference the main compiler project and whatever else they might need, and get a quick scenario working.

They should also be able to make their own NuGet packages for local testing. I don't see the need to include different OS-specific stuff in those. The full enchillada (the current build script) is only called on our GHA for public builds.

**Comment by Jand42** [comment]
@granicz Added new targets, also fixed that all tests are running during a CI build and they are passing.

There is no `tests/allTests` split at the moment, as some compiler tests also require WS main libs to be built to reference them for the test project used. The old WebSharper.Core.JavaScript.Tests project could be moved to be inside WebSharper.Compiler.sln and that could have a NoTests version too then, but I think it's not worth it at the moment, better to have all tests in one place.
So new build targets are (FAKE target names are case-insensitive) : `Build`, `BuildAll`, `Publish`, `Tests`. All produce Release builds by default or Debug if you add the `--debug` flag. An example run: `./build BuildAll --debug --verbose`
