### ISSUE TITLE
Add missing overloads for EventTarget.addEventListener and EventTarget.removeEventListener

### ISSUE THREAD

**Issue by Jooseppi12** [dotnet-websharper/core#1230]
As can be seen [here](https://github.com/dotnet-websharper/core/blob/master/src/stdlib/WebSharper.JavaScript/Dom.fs#L197-L213), both functions are missing the options based overload 

Specification: https://dom.spec.whatwg.org/#interface-eventtarget

**Comment by granicz** [comment]
Hmm, looks like we missed this in https://github.com/dotnet-websharper/core/issues/1207. Thanks @cata for the report!
