### ISSUE TITLE
Provide extra guarantees on Doc.Hydrate calls

### ISSUE THREAD

**Issue by granicz** [dotnet-websharper/core#1262]
As things currently stand, `Doc.Hydrate` does not work with a quoted argument, so `Doc.Hydrate <@ e @>` will, unexpectedly, yield no server-rendered HTML. There are ways to argue that this is by design, and that the solution is to use `Doc.Hydrate(e)` instead, i.e. relying on the implicit auto-quoting mechanism.

I am filing this ticket to guard against unexpected situations when using quoted arguments, so at a bare minimum a warning is raised with their source location to aid debugging.

However, I would also like to explore fixing the gap and making this work for the quoted case as well, AFAIK, there is no real good reason why that should fail. If there is, please comment below.

**Comment by Jand42** [comment]
@granicz F# auto-quotation seems under-documented, the only thing I can find is the design spec https://github.com/fsharp/fslang-design/blob/main/FSharp-4.0/AutoQuotationDesignAndSpec.md#design-overview
This includes the `withValue=true` feature that `Doc.Hydrate` is using.

I know of no F# language feature that would also evaluate the expression for `<@ @>`-quoted expressions.

So I think the best we can do right now is WS giving a warning.
