### ISSUE TITLE
Add Media Capture and Streams API

### ISSUE THREAD

**Issue by Jooseppi12** [dotnet-websharper/core#1276]
https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API

**Comment by ingted** [comment]
Any documentation?

**Comment by granicz** [comment]
I agree - there should be at least tests covering the new APIs. For extra documentation, feel free to PR the [docs repo](https://github.com/dotnet-websharper/docs), currently in development. That said, these are 1-to-1 HTML5/JS bindings and they are heavily documented on the JS side, and any such code would look much the same in F#.
