### ISSUE TITLE
 SRTP failure with System.Int32

### ISSUE THREAD

**Issue by TheAngryByrd** [dotnet-websharper/core#1283]
👋  Hey there,

I stumbled across this edge case with creating a SRTP sum function:

```fsharp
module View = 
        [<Inline>]
        let inline Sum vs =
            (View.Const LanguagePrimitives.GenericZero, vs)
            ||> Seq.fold(fun x y -> 
                View.Map2 ((fun a b -> a + b)) x y 
            )
        
```

```
Could not find method for trait call: op_Addition targets: source:((System.Int32 * System.Int32) -> System.Int32); Could not find method for trait call: op_Addition targets: source:((System.Int32 * System.Int32) -> System.Int32); types: System.Int32, System.Int32
```

https://try.websharper.com/snippet/0000ZD

**Comment by granicz** [comment]
See #1284 as well.

**Comment by granicz** [comment]
(Not to mask the underlying issue, but a quick fix would be to constrain the argument type for `Sum`:)

```fsharp
let inline Sum (vs: seq<View<int>>) =
    ...
```

**Comment by TheAngryByrd** [comment]
> but a quick fix would be to constrain the argument

Yeah that's what I wanted to avoid doing. Having a few bespoke implementations for different numbers isn't hard though :)

**Comment by Jand42** [comment]
@TheAngryByrd Thanks for the report, I indeed see a potential very easy fix for this in the F# operator macro handling.
(Try WebSharper is stuck at WebSharper 4 now, but fix will be in next WebSharper 6 builds soon)

**Comment by Jand42** [comment]
@TheAngryByrd  This is in GH build [6.0.5.244](https://github.com/dotnet-websharper/core/packages/880116?version=6.0.5.244) right now.

Also improved `LanguagePrimitives.GenericZero`, now that will properly resolve for custom types too for the static `Zero` property getter on the type.
