### ISSUE TITLE
`Seq.sum` returns incorrect result for types that define the `get_Zero` operator

### ISSUE THREAD

**Issue by cata** [dotnet-websharper/core#1284]
Please see [this Try WebSharper snippet](https://try.websharper.com/snippet/0000ZE) for the repro.

**Comment by Jand42** [comment]
@cata Thanks, indeed `Seq.sum` and some others probably just have a single implementation for the default `+` operator. I have fixed the related issue #1283 first, as it's needed to process resolving generic operators, looking into this next.

**Comment by cata** [comment]
@Jand42 - awesome, thank you!

**Comment by Jand42** [comment]
These are the `Seq`/`List`/`Array` functions that I would upgrade for better generic handling: `sum`, `sumBy`, `average`, `averageBy`, `min`, `minBy`, `max`, `maxBy`.

Functions using comparisons (sorts) are already working well enough as the actual comparison is handled by a helper that checks for all cases. Similar idea could be implemented for required operations here. Possibly with fallback to a flat simple implementation with direct operator uses, for runtime performance.

**Comment by Jand42** [comment]
@cata This is in GH build [6.0.5.244](https://github.com/dotnet-websharper/core/packages/880116?version=6.0.5.244) right now.

Primitive numeral types still default to a function call that uses plain JS operators inside, but any other type compile to an inline that uses the type's defined `get_Zero` and `op_Addition` members. (And also `DivideByInt` for `average`)

Breaking change: you should now use `sum`, `sumBy`, `average`, `averageBy` functions with resolved generics, or annotate with `[<Inline>]`

**Comment by cata** [comment]
@Jand42 - super, you guys are awesome!
