### ISSUE TITLE
HTML app from the latest template is not running on localhost

### ISSUE THREAD

**Issue by konst-sh** [dotnet-websharper/core#1288]
Seem that I can't view the site from the HTML Websharper project template of v6.0.4.240.
When I running it in debug mode in VS community 2022 it simply opens the project folder in explorer.
There are no option to run it on IIS Express or something. Is it expected behavior?

**Comment by Jand42** [comment]
@konst-sh Yes, the HTML project type is intended for static site generation, no server backend needed other than file hosting.

The SPA and Client-Server projects use ASP.NET Core and support server-side logic and remoting, with the difference that SPA compiles all JS code into a dead-code eliminated bundle script.

**Comment by granicz** [comment]
Yes, you can just open the generated HTML files in the browser.
