### ISSUE TITLE
MathJs Round have no overload for decimal

### ISSUE THREAD

**Issue by diegopego** [dotnet-websharper/core#1304]
let x = WebSharper.MathJS.Math.Round(1.12657m, 2)

This gives the error No overloads match for method 'Round'.

**Comment by Jand42** [comment]
@diegopego Good point, as decimals are translated to a `MathNumber`, it would make sense for MathJS bindings to handle them. You can try adding `T<decimal>` to both `AllValues` and `Numbers` arrays here, then it would generate all the members with overloads for decimals as well

https://github.com/dotnet-websharper/core/blob/438fa773e17893638d902402e89236baae41d37a/src/stdlib/WebSharper.MathJS/Main.fs#L125-L147

**Comment by diegopego** [comment]
If I comment T<float>, I get the same warning with `let x = WebSharper.MathJS.Math.Round(1.12657, 2.0)`
But adding the decimal `T<decimal>` do not generate the members.

If there is a way to test it by compiling just the Math.JS instead of `build.cmd ws-package`? That would help.

One more question: Is there a way to make the intellisense work in `tests/WebSharper.Tests/MathJS.fs`? When I try to access MathJS.Math via Intellisense, I get this message: "The value, constructor, namespace or type 'Math' is not defined."

**Comment by diegopego** [comment]
I'd like to know your opinion on this:
- what type of the number of digits argument should be? System.Math is of type `int`
- should we try to implement MidpointRounding or stick with MathJS default?

System.Math.Round has this signatures:
- System.Math.Round(d: decimal, decimals: int) : decimal // Rounds a decimal value to the nearest integral value, and rounds midpoint values to the nearest even number.
- System.Math.Round(value: float, digits: int) : float // Rounds a double-precision floating-point value to a specified number of fractional digits, and rounds midpoint values to the nearest even number.

WebSharper.MathJS round signature is:
- WebSharper.MathJS.Math.Round(a: decimal, b: decimal) : decimal
- WebSharper.MathJS.Math.Round(a: float, b: float) : float

It would be nice to have MidpointRounding:
- System.Math.Round(d: decimal, decimals: int, mode: MidpointRounding) : decimal
- System.Math.Round(value: float, digits: int, mode: MidpointRounding) : float

MathJS reference:
- https://mathjs.org/docs/reference/functions/round.html
- math.fix(x)	Round a value towards zero.
- math.round(x [, n])	Round a value towards the nearest integer.

**Comment by Jand42** [comment]
@diegopego On the IntelliSense issue: as WIG generator code does not match the final dll, indeed F# code service breaks if cross-project references are enabled, the only workaround is to disable it in VS (I don't know in VSCode...) at 
![image](https://user-images.githubusercontent.com/3116993/210168004-ae5b0248-b671-442f-8a7d-e8225f5ecd77.png)

The `System.Math` class already has a partial proxy at [src/stdlib/WebSharper.Main.Proxies/Math.fs](https://github.com/dotnet-websharper/core/blob/master/src/stdlib/WebSharper.Main.Proxies/Math.fs) but it's possible to add more proxies for static methods in another lib (WebSharper.MathJS.Extensions) the very same way that could hold decimal overloads, and `MidpointRounding` overloads to both which are a bit trickier.

**Comment by diegopego** [comment]
Your sugestion worked. I just commited a PR.


One question: 

Note that if the answer lies in read any docs or books, please point me to the right direction. I want to contribute, not to drain your resources :-)

After reading the tests, I felt that it would be worth adding these too, but they fail


WebSharper.Tests\MathJS.fs:
```
Test "System.Math.Round" {
	let x = 18133887298.441562272235520m
	equal (System.Math.Round(x)) 18133887298m
	equal (System.Math.Round(x, 2)) 18133887298.44m
}

Test "Core.Operators.round" {
	let x = 18133887298.441562272235520m
	equal (round x) 18133887298m
}
```

There are similar passing tests using System.Math:
```
equal (System.Math.Floor x) 18133887298m
equal (floor x) 18133887298m
```
