### ISSUE TITLE
Trialing GraphBasedChecking with latest FCS 

### ISSUE THREAD

**Issue by TheAngryByrd** [dotnet-websharper/core#1329]
👋 I'm trying out some of the new [GraphBasedChecking](https://github.com/dotnet/fsharp/pull/14494) in the F# compiler. It's available [currently in the 7.0.4xxx](https://github.com/dotnet/installer#installers-and-binaries) preview bits. The way to enable it is via `OtherFlags` such as:

```xml
<OtherFlags>$(OtherFlags) --test:GraphBasedChecking</OtherFlags>
```

However, the websharper task fails with this extra argument.

```bash
WEBSHARPERTASK : warning FS1063: Unknown --test argument: 'GraphBasedChecking' 
C:\Users\jimmy\.nuget\packages\websharper.fsharp\6.1.4.277\build\WebSharper.FSharp.targets(50,5): error MSB6006: "wsfsc.exe" exited with code 1. 
```

I did a verbose build with `dotnet build -v d` but I wasn't able to get a stacktrace or anything else that was useful.

**Comment by granicz** [comment]
Yeah, we need to update to the latest FCS and we need to enable passing the new argument. @Jand42 Can we update FCS in the next build (on this or a new ticket)?

**Comment by Jand42** [comment]
@TheAngryByrd @granicz Yes, I can make a new internal (github packages only for now) build with latest preview FCS, I'm tagging changes with this ticket.

**Comment by Jand42** [comment]
@TheAngryByrd Build is [6.1.5.290](https://github.com/dotnet-websharper/core/pkgs/nuget/WebSharper/87261724)

**Comment by TheAngryByrd** [comment]
Seems to not fail anymore! Thanks for jumping on it so quick. Ya'll are awesome :)

Feel free to close this if that's the workflow.

**Comment by Jand42** [comment]
@TheAngryByrd Thanks, but I'll leave this open until there is a stable FCS build containing this flag then I can push out packages to nuget.org.
