### ISSUE TITLE
A wildcard endpoint should not require trailing elements

### ISSUE THREAD

**Issue by rbauduin** [dotnet-websharper/core#1330]
Defining this endpoint;
```
    | [<EndPoint "/admin";Wildcard>] Admin of adminPage:string*args:list<string>
```
Will require the presence of arguments. So it will handle `/admin/user/5` but not `admin/users`.
To handle this last path I need to define an additional endpoint:
```
    | [<EndPoint "/admin";>] AdminWithoutArgs of adminPage:string
```

It would be great if the first endpoint matched `/admin/users` too, giving an empty list of trailing elements.

This would help when embedding a sitelet handling admin pages under the app's main sitelet (which is my use-case here)

**Comment by granicz** [comment]
This largely by design, although I agree it's not the most ideal. I'd just make your endpoint take a single wildcard argument:

```
| [<EndPoint "/admin"; Wildcard>] Admin of args:list<string>
```

 and pattern match on that:

```fsharp
    open WebSharper.Sitelets.UrlHelpers

    [<Website>]
    let Main =
        Application.MultiPage (fun ctx endpoint ->
            match endpoint with
            | EndPoint.Admin(["users"]) ->
                 Content.Text "Users page"
            | EndPoint.Admin(["user"; INT i]) ->
                 Content.Text $"User's item {i} page"
           ...
```

**Comment by rbauduin** [comment]
Thanks for the suggestion, I have adopted it in my code.
I just don't understand the `INT` in `| EndPoint.Admin(["user"; INT i]) ->`. If it's not a typo it's something I don't know.
