### ISSUE TITLE
Add JS.Verbatim and JS.Html helpers

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1333]
To allow printing any code fragments directly (unchecked) to .js output, also html fragments for .jsx.
You can only use constant strings or interpolated strings as argument.

```fsharp
   JS.Verbatim $"console.log({x})" // translated to: `(console.log(x))`
   JS.Html $"<div>{x}</div>" // translated to: `(<div>{x}</div>)`
```

**Comment by granicz** [comment]
Also, when translating placeholders like:

```
<{QRCode} message={value} size="0.5"></{QRCode}>
```

... omit the `{}`'s from around `QRCode`, because we can detect that `<{...}>` and `</{...}>` placeholders yield custom element names.

**Comment by granicz** [comment]
I really find the name `JS.Html` confusing - since it's a trigger to generate .jsx, I'd rename it to `JSX.Html` (my preference) or `JS.JSX`.

**Comment by Jooseppi12** [comment]
Added a JS.Jsx function that is equivalent of the JS.Html function and exposed lowercase variants of those two.
