### ISSUE TITLE
Add ImportFile helper for WIG

### ISSUE THREAD

**Issue by Jooseppi12** [dotnet-websharper/core#1347]
The idea behind this helper is to enable importing other js resources that different bundlers could handle with their plugins.

One usecase would be importing css stylesheets, then a tool like vite or webpack could handle them within their ecosystem.

**Comment by Jand42** [comment]
An example use in WIG: `"default" => T<unit> ^-> T<unit> |> ImportFile (sprintf "highlight.js/styles/default.css" name)`
The import is added as a side-effecting import, without any actual imported values, to be handled by bundlers.
