### ISSUE TITLE
Add the spread operator - Part I

### ISSUE THREAD

**Issue by granicz** [dotnet-websharper/core#1355]
Need the ability to use the spread operator in WebSharper output. This ticket is for the work involved in making the spread operator available in F# scenarios, such as interpolated JSX strings, WebSharper client-side code, etc.

Given that we can't use `...` in as a custom F# operator, one proposal is to use `!...`, as in:

```fsharp
let Foo props =
    let counter = 1
    JS.Verbatim $"""<span style={ {| fontSize="2rem" |} } {!... props}>{counter}</span>
```

**Comment by granicz** [comment]
Resolved in https://github.com/dotnet-websharper/core/commit/46c10a3d30026778bdc221e2bb520d88851f0c46

**Comment by Jand42** [comment]
The `!...` operator has been added for use from F#. No syntax checks are done, uses the JS.Verbatim feature in the background.
