### ISSUE TITLE
Add StubInterfaces option to allow all interfaces to be treated as they would have [<Stub>] attribute

### ISSUE THREAD

**Issue by Jooseppi12** [dotnet-websharper/core#1386]
Adding a `"stubInterfaces": true` wsconfig setting that disregards .NET code semantics for interfaces (automatic unique naming to avoid conflicts) and all interfaces work as stubs.

**Comment by Jand42** [comment]
adding a `"stubInterfaces": true` wsconfig setting that disregards .NET code semantics for interfaces (automatic unique naming to avoid conflicts) and all interfaces work as stubs (as JS mixins)
