### ISSUE TITLE
Import attribute handling

### ISSUE THREAD

**Issue by Jooseppi12** [dotnet-websharper/core#1392]
Consider the following code:

```fsharp
[<Import ("myFunction", "myModule")>]
let myFunction (str: string) = X<unit>
```

The above would describe a function in F# that would be translated to a call `myFunction` from the `myModule` import. At the moment the above code does not compile, as the X<unit> is failing, as this Import is not treated as an inline.

Known workaround at the moment is to apply an inline as well, like this:

```fsharp
[<Import ("myFunction", "myModule"); Inline "$import($str)">]
let myFunction (str: string) = X<unit>
```

Ideally we don't want to rely on the `Inline` to make this work, just applying the import attribute should work.

**Comment by Jand42** [comment]
The `Import` attribute alone has previously not marked the member it's on for client-side. Now it auto-implies `Stub` if there is no `JavaScript` or `Inline` or `Direct` present.

Fixed the behavior of `Stub`+`Import`. For a class, it's valid to mark the class itself with `Import`, then all the members will follow existing `Stub` logic, while the JS class constructor is set by the `Import`.
