### ISSUE TITLE
Question about .NET Framework

### ISSUE THREAD

**Issue by giuliohome** [dotnet-websharper/core#1394]
Hi guys,
I hope to find you well.

Have you dropped development on .NET Framework since Websharper 5.x ?
Or is it possible to target .NET Framework 4.7 and 4.8 ?
Assuming the answer is no, then is there a way to migrate a F# project from .NET Framework 4.6.2 to .NET 8? 

Cheers
Giulio

**Comment by granicz** [comment]
Yes, WebSharper 4.x is the last line that targets .NET Framework. All subsequent major versions (5.x, 6.x, 7.x-beta, and soon 8.x) target net5/6/7/8.

That said, unless your app uses older, non-standard APIs you should be able to move it to .NET 6/8 and WebSharper 6/7/8 relatively easily - give it a go and update the framework reference, update FCore and WebSharper, and report back here if you encounter any issues.

**Comment by giuliohome** [comment]
Perfect, thank you.
