### ISSUE TITLE
Allow name collision on interfaces with Stub

### ISSUE THREAD

**Issue by Jooseppi12** [dotnet-websharper/core#1395]
Consider the following interface:

```fsharp
type MyType =
    abstract MyFunc : string -> string
    abstract MyFunc : string seq -> string
```

The resulting JS should not rename MyFunc to MyFunc_1 to avoid name collision, as we are using this for interop purposes

**Comment by Jand42** [comment]
Modified ticket name: implementing this change for all `Stub`s, using the `stubInterfaces=true` setting is just a special case
