### ISSUE TITLE
C2: improved currying support proposal

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/core#146]
The proposal is to identify curried functions `A -> B -> ... -> R` with JavaScript multi-argument functions `(x: A, y: B, ...) : R` in TypeScript notation. 
### Advantages
1. Easier interop of functional code when using TypeScript / plain JS with WebSharper. For example, `Array.map2 : ('A -> 'B -> 'C) -> 'A[] -> 'B[] -> 'C[]` will be callable from JS/TS as `Array.map2(function (x, y) { return x + y }, [1,2,3], [4,5,6])`.
2. If done correctly, should improve performance of some functional code compared to current implementation where curried function values naively construct multiple closures, even when fully applied
3. Solves the problems with tuples - curried style will become the default, so tuples can always be first class objects, no need to try to unbox them.
### Downsides

The primary downside is that changes to the convention will affect all extensions using `a * b -> c` to describe function values accepting two arguments - which now will have to translate to `a -> b -> c`. This includes core extensions such as jQuery. All code using these extensions will be affected.
### Implementation
1. Detect full calls (calls of a function value with full number of arguments) and treat them specially
2. For the remainder/partial calls, compile function application using an overloaded dynamic operator, based on the following code:

```
#!fsharp

function partial(f, arity, x) {
    function p() {
        Array.prototype.unshift.call(arguments, x);
        return f.apply(this, arguments)
    }
    p.isPartial = true;
    p.arity = arity;
    return p;
}

function smartCall(f, x) {
    var arity = f.isPartial ? f.arity : f.length;
    switch (arity) {
        case 0:
            return f();
        case 1:
            return f(x);
        case 2:
            return function (y) { return f(x, y); }
        default:
            return partial(f, arity - 1, x);
    }
}


function assert(a, b) {
  if (a !== b) {
    console.log("FAIL", a, b);
  }
}

function test() {
  function f(x, y, z) {
    return x + y + z;
  }
  var g = smartCall(f, 1);
  assert(g(2, 3), 6);
  var h = smartCall(g, 2);
  assert(h(4), 7);
}
```

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/146
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2013-09-04T20:44:38.370

**Comment by Tarmil** [comment]
Currying has changed several times since this.
