### ISSUE TITLE
Certain characters cause page templating to break

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/core#175]
Repro:

Put something like: 

```
#!html

<img src="http://placehold.it/400x100&text=Logo"/>
```

into Main.html sitelet template and then try loading the site.

Error:

'=' is an unexpected token. The expected token is ';'. Line 26, position 55.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 26, position 55.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[XmlException: '=' is an unexpected token. The expected token is ';'. Line 26, position 55.]
   IntelliFactory.WebSharper.Sitelets.Content.unpack@402(FSharpChoice`2 x) +178
   IntelliFactory.WebSharper.Sitelets.Content.f@1-46(FSharpFunc`2 parse, String path, FSharpRef`1 cell, FSharpFunc`2 reload, Unit unitVar0) +220
   IntelliFactory.WebSharper.Sitelets.clo@406-61.Invoke(Unit unitVar0) +171
   IntelliFactory.WebSharper.Sitelets.WithTemplate@479.Invoke(Context`1 ctx) +140
   IntelliFactory.WebSharper.Sitelets.WebUtils.respond(Sitelet`1 site, HttpContext ctx, Request req, Object action) +166
   IntelliFactory.WebSharper.Sitelets.HttpHandler.System-Web-IHttpHandler-ProcessRequest(HttpContext ctx) +63
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +341
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/175
- Originally reported by: [perfectshuffle](http://bitbucket.org/perfectshuffle)
- Originally created at: 2013-10-24T19:52:55.290

**Comment by Tarmil** [comment]
This is a known issue of WebSharper.Html's templating; UI doesn't have this problem.
