### ISSUE TITLE
Having to add FSharp.Core in fsproj file

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/core#181]
Not sure why but I remembered I had to add the following in the last item group to avoid getting an ASP.NET error at runtime after creating a new project:

```
<Reference Include="FSharp.Core, Version=$(TargetFSharpCoreVersion), Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
  <Private>True</Private>
</Reference>
```

Today I set up my boss for a new project and he came up again with the same ASP.NET error and I was lucky to remember I could copy this from one of my other project.

Let me know if you want me to package up a repo that reproduces the problem, perhaps it's the way I had the websharper template projects.

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/181
- Originally reported by: David Grenier
- Originally created at: 2013-11-05T23:32:10.109

**Comment by Tarmil** [comment]
WebSharper now references the FSharp.Core nuget package.
