### ISSUE TITLE
For bundle projects, allow downloading resources mentioned by URL

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/core#225]
Currently they are linked-to by URL, but this is not a good idea for mobile applications. Should be a switch allowing to directly download and put into the bundle. 

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/225
- Originally reported by: [IntelliFactory](http://bitbucket.org/IntelliFactory)
- Originally created at: 2014-03-17T20:09:47.472

**Comment by Tarmil** [comment]
Duplicate: #596
