### ISSUE TITLE
Websharper 2.5.111.45 failed to translate List<T>.GetEnumerator()

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/core#251]
```
#!f#

let children = List<Component>()
for c in children do c.Update()

```

error WebSharper: Failed to translate a method call: GetEnumerator(..) [System.Collections.Generic.List`1].

but 

```
#!f#

for i = 0 to children.Count - 1 do children.[i].Update()
```

work!!!

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/251
- Originally reported by: Anonymous
- Originally created at: 2014-06-03T11:16:13.877

**Comment by Tarmil** [comment]
IEnumerator has been reworked since, and this now works.
