### ISSUE TITLE
Project scaffolding support

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/core#269]
Getting started on Mono with Emacs is not that fun currently. Could allow `WebSharper.exe scaffold` command or similar, to instantiate templates.

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/269
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2014-07-31T18:49:44.751

**Comment by Tarmil** [comment]
`dotnet new` is now the way to go.
