### ISSUE TITLE
Report compile error when can't encode/decode RPC args/result

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/core#289]
Previously wrongly typed RPC arguments reported a warning, result haven't.

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/289
- Originally reported by: András Jankó
- Originally created at: 2014-09-24T11:22:33.622

**Comment by V0d01ey** [comment]
Now if an argument/result-class don't have a default constructor the analyzer don't report a warning.
Should I open a new issue? Or this issue can be reopened?

**Comment by Jand42** [comment]
@V0d01ey Not even compilation fails? I will check this. The C# analyzer is not doing the RPC signature verification right now as it needs reflection (possibly this will change if RPC/and sitelets json behavior are unified).

**Comment by V0d01ey** [comment]
@Jand42 , yes, the error reveals itself by crash only when you try to send such object (not null) from client to server. And inside complex structure it is not trivial to locate the problem.

**Comment by Jand42** [comment]
@V0d01ey Thanks for the report! I have created ticket https://github.com/dotnet-websharper/core/issues/989.
