### ISSUE TITLE
Compile WebSharper library project directly to Javascript

### ISSUE THREAD

**Issue by xavierzwirtz** [dotnet-websharper/core#348]
I have created a Websharper library project using the template added to VS by Websharper. How do I compile this project directly to a Javascript file?

**Comment by VoiceOfWisdom** [comment]
I can see the `-js` switch on `Websharper.exe`, don't see anyway to tell websharper to add that when building from VS.

**Comment by Tarmil** [comment]
This is now doable using the "jsOutput" option in wsconfig.json.
