### ISSUE TITLE
Opening WebSharper.Main.fsproj causes Visual Studio crash

### ISSUE THREAD

**Issue by xavierzwirtz** [dotnet-websharper/core#353]
Opening `src\stdlib\WebSharper.Main\WebSharper.Main.fsproj` causes VS to crash. The main `WebSharper.sln` also crashes, unless that reference is removed.

Running `build.cmd` builds `src\stdlib\WebSharper.Main\WebSharper.Main.fsproj` successfully, its just VS that cant open the project.

Running Visual Studio 2013 on Windows 8.1 x64.

**Comment by VoiceOfWisdom** [comment]
Oddly, `WebSharper.Main.fsproj` opens perfectly fine in VS if I remove:
```xml
<ProjectReference Include="..\WebSharper.JQuery\WebSharper.JQuery.fsproj">
    <Name>WebSharper.JQuery</Name>
    <Project>{730ae40a-001c-4137-972d-898dc7c2bf0a}</Project>
    <Private>True</Private>
</ProjectReference>
```

`build.cmd` no longer successfully compiles however.

**Comment by VoiceOfWisdom** [comment]
99% certain this is the same bug as #336.

**Comment by ca-ta** [comment]
I can repro this as well. VS 2013 Ultimate + update 4, Win 8.1 x64

**Comment by Tarmil** [comment]
No longer an issue in WS4.
