### ISSUE TITLE
Pattern guards result in combinatory explosion of code size

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/core#393]
For example the following code:

``` fsharp
match x with
| [a;b;c] when C -> A
| _ -> B
```

is compiled to nested ifs:

``` javascript
if (x.$ == 0) {
  if (x.$0.$ == 0) {
    if (x.$0.$0.$ == 0) {
      if (C) {
        A
      } // and then every "else" body contains B
```

**Comment by ca-ta** [comment]
I can confirm this is a real problem in the wild - I've had to significantly adjust some parser code - a 28K F# file got expanded to about 600K worth of JavaScript.

**Comment by Tarmil** [comment]
As I have since then found out, this problem actually comes from F# quotations: https://github.com/Microsoft/visualfsharp/issues/307 WebSharper just faithfully translates these huge quotations.

**Comment by ca-ta** [comment]
Thanks Loïc - good to know :+1: 

That somewhat hints to why the compile time had taken a big hit as well...
in my case I've addressed the bulk of the issue by enclosing pattern matches with guards within active patterns and then using those. That way the damage is limited to functions with a very small number of matches - that helped a lot: I eliminated about 560K of JS by making a relatively small number of changes.

**Comment by Tarmil** [comment]
This is not a problem anymore in WebSharper 4.
