### ISSUE TITLE
Creating a new project specified a HintPath too specific

### ISSUE THREAD

**Issue by FrankBro** [dotnet-websharper/core#505]
Trying to get a new project to compile on appharbor, I saw that for some reason, creating a new project added a HintPath that backtracks too hard and become too specific. Here is an example.

```
<Reference Include="IntelliFactory.Xml">
  <HintPath>..\..\..\..\..\..\..\Users\Francois\documents\visual studio 2015\Projects\Rpg\packages\IntelliFactory.Xml.0.6.63.95\lib\net40\IntelliFactory.Xml.dll</HintPath>
  <Private>True</Private>
</Reference>
<Reference Include="mscorlib" />
```

**Comment by FrankBro** [comment]
Pretty weird, I created another project and went to edit the project, expecting the problem to happen again but it didn't. Don't think I did anything special in either case.

**Comment by Tarmil** [comment]
Closing as failed to reproduce.
