### ISSUE TITLE
JS bundle is created after post-build event

### ISSUE THREAD

**Issue by dgrechka** [dotnet-websharper/core#528]
Using WebSharper 3.6.7.227.
1. I create the project with
          `<WebSharperProject>Bundle</WebSharperProject>`
2. Declare post build event e.g.
          `<PostBuildEvent>dir "../Content"</PostBuildEvent>`
3. I expect to see xxxxx.head.js, xxxx.js, xxxxx.min.js in the dir command output when the post buildevent ios triggered, but dir does not show these files.
   These files are created in Content directory after the post build event is already executed

**Comment by ca-ta** [comment]
FWIW, 

Here are two approaches I am currently using:
* if all you need is to generate the *.js files in different folder, you can modify `WebSharperBundleOutputDir` in your project:
```
    <WebSharperBundleOutputDir>Path_To_Some_Other_Folder</WebSharperBundleOutputDir>
```
* If you want ot do more complex stuff, modify your project to perform those operations in a target that executes after `WebSharperBundle`, e.g.:
```
  <Target Name="Deploy" AfterTargets="WebSharperBundle">
    <Copy SourceFiles=".\Content\YourApp.js" DestinationFolder="Path_To_Some_Other_Folder" />
  </Target>

```

**Comment by Tarmil** [comment]
Yes, @ca-ta is right, if you want to run a command after bundling then you should use `AfterTargets="WebSharperBundle"`. I am tagging this issue as "documentation", because it needs to be better explained in the docs.

**Comment by cgravill** [comment]
Does "WebSharperBundle" still get called in 4.x / Zafir? I have some actions set to AfterTargets that don't seem to be triggered now I've ported over.

Any pointers to documentation it it's now available on this would be great, thanks.

**Comment by Jand42** [comment]
In 4.0-beta, `CoreCompile` does everything for F#, it replaces the call to `fsc.exe` to `wsfsc.exe` by setting `FscToolPath`/`FscToolExe` properties.

**Comment by cgravill** [comment]
Thanks @Jand42 I'm getting outputs again with this target.
