### ISSUE TITLE
403 forbidden when make rpc call (ubuntu 16.04)

### ISSUE THREAD

**Issue by flypixel** [dotnet-websharper/core#603]
Hello, I have a problem on Ubuntu 16.04, when I use this sample:

``` fsharp
#I "./packages/"
#load "WebSharper.Warp/tools/reference-nover.fsx"
open WebSharper
open WebSharper.JavaScript
open WebSharper.Sitelets
open WebSharper.UI.Next
open WebSharper.UI.Next.Html
open WebSharper.UI.Next.Client

module Remoting =
    [<Rpc>]
    let sayHello() = 
        async.Return "Hello!"

[<JavaScript>]
module Client =
    let main() =
        View.Const ()
        |> View.MapAsync Remoting.sayHello
        |> View.Map text
        |> Doc.EmbedView

module Server =
    let site =
        Application.SinglePage (fun _-> 
            Content.Page [ client <@ Client.main() @> ])

do Warp.RunAndWaitForInput Server.site |> ignore
```

When I run it, I got a 403 error when rpc call was occurred
![screenshot from 2016-08-30 15-48-09](https://cloud.githubusercontent.com/assets/14139485/18089936/f3dff2ea-6eca-11e6-88c2-fa21a5daed83.png)
![screenshot from 2016-08-30 15-49-55](https://cloud.githubusercontent.com/assets/14139485/18089937/f6a21cba-6eca-11e6-8b91-8b752862c0b3.png)
**Update:**
I try to back to the previous version of WebSharper, and that is I found out:
with this 
[paket.dependencies.txt](https://github.com/intellifactory/websharper/files/447247/paket.dependencies.txt)
[paket.lock.txt](https://github.com/intellifactory/websharper/files/447246/paket.lock.txt)
everything works correct, but with this 
[paket.dependencies.txt](https://github.com/intellifactory/websharper/files/447255/paket.dependencies.txt)
[paket.lock.txt](https://github.com/intellifactory/websharper/files/447256/paket.lock.txt)
Rpc isn't working

**Comment by Jand42** [comment]
Thanks for the report, we will investigate. This is not platform specific but some general issue with RPCs inside Owin, "Self-Hosted Client-Server Application" project template is also broken (tested on Windows).

**Comment by Tarmil** [comment]
I just published WebSharper 3.6.16 which should fix this issue. Can you update to it and verify that it is the case?

**Comment by flypixel** [comment]
Sorry, but it still is not working. I use next code for testing (first is an old version that works fine, and second is a last version that doesn't work)
[rpctest (working).zip](https://github.com/intellifactory/websharper/files/450887/rpctest.working.zip)
[rpctest (not working).zip](https://github.com/intellifactory/websharper/files/450888/rpctest.not.working.zip)
Also I send you a screen-shot. When I push the button you can see a message in firebug on net->xml tab. I don't know really, maybe it can be helpful.
![screenshot from 2016-09-02 02-02-24](https://cloud.githubusercontent.com/assets/14139485/18187553/3bf48386-70b3-11e6-9870-f0a8c4dd6ab3.png)

**Comment by Tarmil** [comment]
OK, your code works correctly on Windows but I can indeed reproduce the issue on Linux. It seems to be caused by the anti-CSRF protection: if you call `WebSharper.Web.Remoting.DisableCsrfProtection()` before starting the Warp server, the RPC works. I'm investigating more into this.

**Comment by Tarmil** [comment]
The issue is confirmed fixed on mono, and I will trigger a publish soon.

**Comment by flypixel** [comment]
Thanks

**Comment by flypixel** [comment]
Sorry again. Maybe I didn't understand correctly, so I won't reopen this issue. But as you say Rpc works fine with this 

> if you call `WebSharper.Web.Remoting.DisableCsrfProtection()` before starting the Warp server, the RPC works

but without this code it's still not working. Thank you.

**Comment by Tarmil** [comment]
Yes sorry I haven't published the fix to NuGet yet. I will do it on Monday.

**Comment by o1lo01ol1o** [comment]
I'm running into the same problem using the Suave-websharper template app in windows.  Adding `WebSharper.Web.Remoting.DisableCsrfProtection()` fixes the problem.  `paket.dependancies` are as follows:
```
nuget Microsoft.Owin 3.0.1
nuget Mono.Cecil 0.9.6.4
nuget Owin 1.0
nuget Suave 1.1.3
nuget WebSharper 3.6.18.241
nuget WebSharper.Owin 3.6.13.132
nuget WebSharper.Suave 3.6.13.40
nuget WebSharper.UI.Next 3.6.15.211
```

**Comment by endeavour** [comment]
I also have this issue with Websharper + Suave. It only occurs on the initial page load however. Refreshing a page for the 2nd time fixes the issue.

I think this is a timing issue with when the CSRF token cookie is set. The RPC call is made before the CSRF cookie exists on the client so the calls fail. When reloading the page the cookie is now there and it succeeds.

**Comment by Tarmil** [comment]
Yes indeed, sorry about that. The client-side should retry the request once if it detects that it has been rejected due to CSRF missing, but this has been broken. I'll fix it ASAP.

**Comment by endeavour** [comment]
Any update on this? Disabling CSRF protection is a pretty undesirable workaround.

**Comment by Tarmil** [comment]
I narrowed down the issue, this is now working for me with the latest (both on websharper3x branch and master). We should have this fix pushed on nuget within a day.
