### ISSUE TITLE
Bug: hash collisions cause wrong behaviour in Dictionary

### ISSUE THREAD

**Issue by FilippoPolo** [dotnet-websharper/core#624]
Hi all,

I've found that the W# implementation of Dictionary does not seem to handle hash collisions. This can result in unpredictable buggy behaviour. Here is a repro:

  let test() =
    let d = new System.Collections.Generic.Dictionary<Map<int,int>, string>()
    let m1:Map<int,int> = Map.empty
    let m1 = Map.add 0 2 m1
    let m1 = Map.add 3 1 m1
    let m1 = Map.add 4 1 m1
    let m2:Map<int,int> = Map.empty
    let m2 = Map.add 0 1 m2
    let m2 = Map.add 3 1 m2
    let m2 = Map.add 5 1 m2
    d.Add(m1, "foo");
    d.ContainsKey m2

The code above will correctly return FALSE on .NET, and wrongly return TRUE on W#.

I have tested this in both the latest W# 3 and the latest W# 4.

**Comment by FilippoPolo** [comment]
Also, here is an example that works fine in .NET, but throws an exception in W# (3 or 4):

  let test_insertion() =
    let d = new System.Collections.Generic.Dictionary<Map<int,int>, string>()
    let m1:Map<int,int> = Map.empty
    let m1 = Map.add 0 2 m1
    let m1 = Map.add 3 1 m1
    let m1 = Map.add 4 1 m1
    let m2:Map<int,int> = Map.empty
    let m2 = Map.add 0 1 m2
    let m2 = Map.add 3 1 m2
    let m2 = Map.add 5 1 m2
    d.Add(m1, "foo");
    d.Add(m2, "bar");

**Comment by Jand42** [comment]
@FilippoPolo Thanks for the report!

**Comment by FilippoPolo** [comment]
Thanks for the prompt action! Is there any chance you could patch W# 3 as well? Although we are testing 4, we are not quite ready to switch versions in production yet, but this problem is fairly worrying for us.
