### ISSUE TITLE
Merge the JS module from WebSharper.Main with the JS type from WebSharper.JavaScript

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/core#807]
The former is entirely comprised of inlines, I think its place should be in the WIG definition. This would also make it more consistent to use from C#, instead of separate JS and JSModule.

The only non-trivial part of this would be moving `AnimationFrameResource`, which is not a simple `BaseResource` and therefore can't be defined in WIG. I guess it would have to be defined in WS.Core.

**Comment by Jand42** [comment]
Moved this to 4.3 column, we should not introduce binary breaking changes in patch releases.

**Comment by Tarmil** [comment]
A difficulty with this: WIG is unable to define a generic F# value `JS.Undefined : 'T`.

**Comment by Tarmil** [comment]
The part of `JS` that is currently defined in the `WebSharper.JavaScript` assembly is just functions that are, in js, defined on the `window` object, plus `Inline` which is a WebSharper construct. So what we should do is:

1. Ensure that these functions are defined on the `Window` proxy.
2. Define aliases for them in the module `WebSharper.JavaScript.JS` in the `WebSharper.Main` assembly.
3. Remove the class `WebSharper.JavaScript.JS` from the `WebSharper.JavaScript` assembly.
