### ISSUE TITLE
Caching improvements for the Scripts/ folder

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/core#88]
Improve loading of Scripts to speed websites up. Ideas:
- generate unique names based on content and serve with long expiry
- combine multiple JS files into a single app

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/88
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2012-09-28T19:38:50.070

**Comment by Tarmil** [comment]
Point 1 was fixed in #722, point 2 is bundles / SPA apps.
