### ISSUE TITLE
Sitelets with MVC

### ISSUE THREAD

**Issue by intellifactory-bb** [dotnet-websharper/core#89]
Currently sitelet module conflicts with MVC. Idea: make sitelets runnable as part of the MVC framework, to be able to plug them into the MVC routing.

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/89
- Originally reported by: Anton Tayanovskyy
- Originally created at: 2012-10-10T23:32:51.232

**Comment by Tarmil** [comment]
Outdated since [WebSharper.AspNetMvc](https://github.com/dotnet-websharper/aspnetmvc).
