### ISSUE TITLE
Precompiled quotations are keyed only by filename+position

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/core#890]
They should additionally be keyed by assembly name.

**Comment by Jand42** [comment]
This is metadata-breaking. Current flag is `4.2`, make sure to modify this to `4.2.x` when committing: https://github.com/dotnet-websharper/core/blob/master/src/compiler/WebSharper.Core/Metadata.fs#L492

**Comment by Tarmil** [comment]
Unfortunately we couldn't find a way to reliably get the assembly name of the quotation at runtime. This is a rare enough issue that an improved error message is sufficient, at least until we can find a complete fix.
