### ISSUE TITLE
Support for standalone .js output to be used as a library

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#900]
## The problem

Current bundling creates a single `.js`, but by default only includes code that are directly or indirectly used by the method marked as `SPAEntryPoint`.

When turning off dead code elimination, up to `4.1.4.189` it created a single .js containing all current and referenced code. Since `4.1.4.189`, if source mapping is also off, bundling opts for a faster approach of just concatenating existing `.js` output of assemblies which contain code needed for running the `SPAEntryPoint`.

Both older and newer logic are not optimal for the valid use case of trying to create a `.js` output to be used as a JS library instead of main application logic. The older output with DCE off was unnecessarily big (containing whole of WS core library and proxy code and everything else referenced), the newer too small (if entry point is just a empty fake method, not even including WS code libraries).

## Proposal

Add proper support for creating single `js` output that is intended to be used as a standalone library.

* Project type remains a Bundle/BundleOnly, but a new `JavaScriptExport` attribute allows defining the scope of the API to be exposed for the assembly. Examples:
    * `[<assembly: JavaScriptExport>]` marks all of current assembly to be always fully included in output.
    * `[<assembly: JavaScriptExport("AssemblyName")>]` marks another assembly to be always fully included in output.
    * `[<assembly: JavaScriptExport(typeof<T>)>]` marks a type to be always fully included in output.
* If there are any `JavaScriptExport` attributes then `SPAEntryPoint` is optional. But the two can also coexist: this creates .js for an SPA, with the extra exports not DCE-d away (useful for debugging helpers).
* DCE would then work on a starting node set determined by all/any `SPAEntryPoint` and `JavaScriptExport` attributes.

Main advantage of this over current workaround of turning off DCE: all of current API is available in output, but only the minimal needed part of WebSharper core library code is included. Also, resources (external scripts or script links) can be explored for the entire scope, not just for the entry point. (Currently external resources are still determined by dependencies of the entry point, turning off DCE only affects the .js output pruning.)

Note: WebSharper currently does not track member accessibility modifiers, so JS output has all private/public members in the scope. Access modifiers carried over to output is planned for WebSharper 5.0 (TypeScript output).

**Comment by cgravill** [comment]
As a reference point: what we currently do is have a module and put all the functions and types that we wish to call from JavaScript (or TypeScript) more easily discoverable. It also gives us a place to use F# to reshape APIs to be more JavaScript friendly. Would it be possible to use `[<assembly: JavaScriptExport(typeof<T>)>]` against a module then trace through all types? If so that would be extremely useful for us.

Lack of accessibility modifiers aren't an issue for us - I wrote some code to codegen TypeScript corresponding to WebSharper enough to cover our usage. It would be great to switch to using something more complete and help with that instead.

**Comment by cata** [comment]
Another data point: we are using the `WebSharper.Compiler` package to generate JavaScript plug-ins that run in the browser. We strictly need the plugin-specific JavaScript , with no dependencies included (we ensure they are available at runtime). 
To achieve this, we are using `WebSharperFSharpCompiler.Compile` and  `CreateBundleJSOutput` directly to avoid packing dependencies and dead code elimination. 
Plug-in generation happens in-process - this approach also avoids loading the generated plug-in assemblies in memory and reduces IO as much as possible ( not entirely - we generate temporary files to run the F# compilation and project check, but at least we do not rewrite the output dll).

The proposed enhancements would allow us to get rid of the dummy SPA entry point we are currently injecting to make `CreateBundleJSOutput`  work.  👍

**Comment by Jand42** [comment]
@cgravill This is now released in `4.2.13.263` as described here, more documentation upcoming. Sorry for the long delay...

If a type/module is marked `JavaScriptExport` (either directly or with `JavaScriptExport("FullTypeName")` or `JavaScriptExport(typeof<MyType>)`, then all nested types/modules contained within are part of the export file. When using a `BundleOnly` project, you can also set `jsOutput` in `wsconfig.json` to write the `.js` somewhere independent of the whole bundle project output.

**Comment by Jand42** [comment]
@cata I have made `CreateBundleJSOutput` not be strict about an `SPAEntryPoint` defined, one less workaround needed. Not much other change on the Frontend API side, yet.

**Comment by cgravill** [comment]
That's great news, I'll give it a try when I get a chance.

**Comment by cata** [comment]
@Jand42 - thank you for the change!

**Comment by Jand42** [comment]
@cgravill @cata This blog entry gives some guidance about using `JavaScriptExport` https://forums.websharper.com/blog/85353
