### ISSUE TITLE
build failing - and what worked for me

### ISSUE THREAD

**Issue by cata** [dotnet-websharper/core#903]
Hi guys,

I've recently tried to build core and failed. What fixed it for me was adding a `global.json` file with:

```
{
  "sdk": {
    "version": "2.1.4"
  }
}
```
Otherwise my computer was picking up `2.1.100-preview-007326` and the build failed with
```
System.Exception: dotnet restore "WebSharper.sln" failed with code 1
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
```

**Comment by Tarmil** [comment]
I could reproduce this with the current preview (2.1.300-preview2-008062), and there's this error just above:

`C:\if\websharper\tests\Web\Web.csproj(158,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.1.300-preview2-008062\Microsoft\VisualStudio\v15.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

The strange thing is that this file (and the whole `VisualStudio` folder) doesn't exist in the 2.1.4 sdk either. The failing line is:

`<Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />`

so my guess is that the preview SDK sets the `VSToolsPath` variable, whereas 2.1.4 doesn't. Replacing the condition in the above line with `Exists('$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets')` makes the build succeed, so I think that's what I'll do.

**Comment by lopezdp** [comment]
> I could reproduce this with the current preview (2.1.300-preview2-008062), and there's this error just above:
> 
> `C:\if\websharper\tests\Web\Web.csproj(158,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.1.300-preview2-008062\Microsoft\VisualStudio\v15.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`
> 
> The strange thing is that this file (and the whole `VisualStudio` folder) doesn't exist in the 2.1.4 sdk either. The failing line is:
> 
> `<Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />`
> 
> so my guess is that the preview SDK sets the `VSToolsPath` variable, whereas 2.1.4 doesn't. Replacing the condition in the above line with `Exists('$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets')` makes the build succeed, so I think that's what I'll do.

Yeah buddy! This at least got rid of the error so that the build could proceed and I could run into the next error!!! lol 

Thank you sir. Error gone but at least it tells me nothing to do because none of the projects contain projects to restore!
