### ISSUE TITLE
Implement proper argument parsing

### ISSUE THREAD

**Issue by granicz** [dotnet-websharper/core#910]
When I run `wsfsc.exe` without any arguments, I get this non-friendly output:

```
C:\>wsfsc.exe
WebSharper error FS9001: Global error 'Value cannot be null.↔Parameter name: path1' at    at System.IO.Path.Combine(String path1, String path2)↔   at WebSharper.FSha
rp.Program.compileMain$cont@260(String[] argv, Unit unitVar)↔   at WebSharper.FSharp.Program.main(String[] argv)
```

This needs to give me a nice argument listing with a version information about the underlying compilers.

**Comment by Jand42** [comment]
Also:

* Make sure to print argument parsing errors in a clean way (single helpful message, no stack trace)
* If there are no `--project` arguments specified, look for a single `.fsproj`/`.csproj`
* Do not fail on having multiple `--ws` arguments, use the last one for project type (multiples can happen if a NuGet update does not uninstall `Import` for targets file correctly.)
* Add `--help` options to print WebSharper compilation arguments and also `unpack`/`html` commands inherited from WebSharper 2/3

**Comment by Jand42** [comment]
TODO:

* Include used version of Roslyn/FCS in info

**Comment by Tarmil** [comment]
I'm implementing the Roslyn/FCS info, plus this:

* more consistent syntax for boolean flags: `--foo` or `--foo+` sets to true, `--foo-` sets to false (like fsc).
