### ISSUE TITLE
WebSharper.Compiler nuget package does not include MonoCecil dependency

### ISSUE THREAD

**Issue by cata** [dotnet-websharper/core#912]
I see the dependency specified in  `paket.template`, but it's missing from the generated nuspec file.

**Comment by Jand42** [comment]
It is in the latest 4.2-beta release which contains this change: a4244d3303598709a8eb084edbfd7dcae7b0dc5f
https://www.nuget.org/packages/WebSharper.Compiler/4.2.1.223-beta

I was considering of making FCS and Roslyn dependencies too, but someone might use only one of the languages.

**Comment by cata** [comment]
Thanks - we should switch to 4.2 :-)
