### ISSUE TITLE
Invalid output code when using a generic type alias to a struct union

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/core#914]
This issue appeared recently, I suspect the fix for #906 to be causing it.

```fsharp
    type Result<'T> = Result<'T,string>

    let get() : Result<int>= Ok 42

    let test() =
        match get() with
            | Ok y -> string y
            | _ -> "Error"
```

The above returns "Error"; without the `Result<int>` type annotation, it returns "42".

```javascript
// Faulty output (with type alias annotation)
 HelloWorld.test=function()
 {
  HelloWorld.get();
  return void 0==0?Global.String(void 0):"Error";
 };

// Correct output (without type alias annotation)
 HelloWorld.test=function()
 {
  var m;
  m=HelloWorld.get();
  return m.$==0?Global.String(m.$0):"Error";
 };
```

(Thanks @cata for reporting this on gitter and working together on a repro!)

**Comment by Tarmil** [comment]
Also to note is that this only happens if the aliased type is a struct.

**Comment by Tarmil** [comment]
Actually this still fails when reverting the #906 fix, so that's not the cause.

**Comment by Jand42** [comment]
Issue was not all uses of looking at F# types resolved type aliases. For example accessing a struct union is wrapped in an `AddressOf` case by FCS, and the code ignoring this when it is a local variable was not resolving type aliases.

**Comment by cata** [comment]
@Tarmil - Thanks for fixing this!
