### ISSUE TITLE
WebSharper.Compiler package dependencies

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#929]
Currently, there is a single `WebSharper.Compiler` package that contains all compiler dlls as `lib` references. It has no package dependencies on either `FSharp.Compiler.Service` or `Microsoft.CodeAnalysis.CSharp` right now, with the intention that using only one of F# or C# paths would not need installing both FCS and Roslyn.

This requires that in any project using `WebSharper.Compiler` for compiling from source, compatible versions of FCS and/or Roslyn packages needs to be added by hand (and also kept compatible by hand when the FCS/Roslyn version used by WebSharper is changing).

Proposal is to break this up into multiple packages:

* `WebSharper.Compiler.Common` would contain the `WebSharper.Compiler.dll` and depend on `Mono.Cecil` and `WebSharper` packages. It would be useful for apps that want to compile F# quotations (but not source) at runtime, and tools that inspect WebSharper metadata.
* `WebSharper.Compiler.FSharp` would contain the `WebSharper.Compiler.FSharp.dll` and depend on `WebSharper.Compiler` and compatible version(s) of `FSharp.Compiler.Service`.
* `WebSharper.Compiler.CSharp` would contain the `WebSharper.Compiler.CSharp.dll` and depend on `WebSharper.Compiler` and compatible version(s) of `Microsoft.CodeAnalysis.CSharp`.

Optionally:
* `WebSharper.Compiler` package would continue to exist but no content in itself, just a superset of `WebSharper.Compiler.FSharp` and `WebSharper.Compiler.CSharp`.
* `WebSharper.Sitelets.Offline` would contain the `WebSharper.Sitelets.Offline.dll` and depend on `WebSharper.Compiler`. This is needed for generating WebSharper offline html+js sites programmatically (not used anywhere afaik, API could use some improvement for this to be easier to set up if needed)

**Comment by cata** [comment]
This would work great for our current use case!
With this in place, we would be using `WebSharper.Compiler.FSharp` and remove the explicit dependencies we currently hold on `Mono.Cecil` and `FSharp.Compiler.Service`

**Comment by Tarmil** [comment]
This was done in v4.3.
