### ISSUE TITLE
WebSharper 4 Suave-hosted site -- About --  File not found

### ISSUE THREAD

**Issue by nightroman** [dotnet-websharper/core#933]
Environment and steps

- Visual Studio 15.6.4
- Visual Studio WebSharper extension 4.2.8.227
- New project from Visual F# \ WebSharper \ WebSharper 4 Suave-hosted site
- Build
- Run
- Open the browser (Chrome) and navigate to "http://127.0.0.1:8080"

At this point all looks good and the main page is shown correctly.

- Click "About" in the navigation bar.

As a result with "http://127.0.0.1:8080/about" we get the page with "File not found".

This is not 100% repro. Sometimes the About page is shown, sometimes it is not.

**Comment by Tarmil** [comment]
Thanks for the detailed repro! I'm able to reproduce this. As you said, it doesn't happen every time; the only consistency I can see is that once it has failed, it keeps failing every time until the server is restarted. It's quite strange, I don't have any conjecture yet about why it happens. Investigating.

**Comment by nightroman** [comment]
The issue is no more after https://github.com/dotnet-websharper/suave/issues/12 (expected or not).
I am closing this.
