### ISSUE TITLE
WebSharper 4 -- obscure error if WebSharper output is not specified

### ISSUE THREAD

**Issue by nightroman** [dotnet-websharper/core#934]
Given `WebProjectOutputDir` is missing in the project file and `outputDir` is
missing in *wsconfig.json*, `dotnet build` fails with a very obscure error:

```
FSC : WebSharper error FS9001: Global error 'The option value was
None↔Parameter name: option' at    at
Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption` 1 option)↔   at
WebSharper.Compiler.CommandTools.ExecuteCommands.Unpack(WsConfig settings)↔
at WebSharper.FSharp.Program.Compile$cont@191-2(WsConfig config, Boole an
isBundleOnly, Loader loader, FSharpList`1 refs, Task`1 wsRefsMeta, Compilation
comp, Unit unitVar)↔   at WebSharper.FSharp.Program.Compile$cont@61(WsConfig
confi g, WarnSettings warnSettings, String thisName, Unit unitVar)↔   at
WebSharper.FSharp.Program.compileMain$cont@271(String[] argv, Unit unitVar)↔
at WebSharper.FSha rp.Program.main(String[] argv)
[C:\Users\...]
```

It is a user error indeed that the output is not specified. But it is not impossible.
It happened to me on converting a WebSharper v3 project to v4.
Due to the obscure error, it took a long time to find my mistake.

**Comment by Jand42** [comment]
Thanks for the report! Error reporting around unpacking will need to be revised and improved for #664 anyways, so this will definitely will be improved in version 4.3. In the meantime, a descriptive error will be given in the next bugfix release.
