### ISSUE TITLE
Seq.chunkBysize exception

### ISSUE THREAD

**Issue by cata** [dotnet-websharper/core#935]
For certain sequence expressions, `Seq chunkBySize` throws exception if the resulting sequence is shorter than the maximum chunk size.

See repro here: http://try.websharper.com/snippet/0000KZ

**Comment by Jand42** [comment]
Thanks for the report! Indeed, the `chunkBySize` proxy is calling `MoveNext` again on a sequence object when it has already ran out, this can fail, and so needs a fix https://github.com/dotnet-websharper/core/blob/060d63aac7a0efe0112e00556e6645182bcdfd53/src/stdlib/WebSharper.Main.Proxies/CollectionInternals.fs#L146

**Comment by cata** [comment]
@Jand42 - thank you for the fix!
