### ISSUE TITLE
Inferred sitelet: "GET /" union case prevents other cases from being parsed

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/core#940]
When only some union cases have an explicit method, then the other cases are never parsed. For example, given this:

```fsharp
type Fails =
    | [<EndPoint "GET /">] Home
    | [<EndPoint "/about">] About
```

A GET request to `/about` is **not** parsed into `About`, whereas it should be.

This issue does not manifest in the following variants (ie `GET /about` is parsed correctly):

```fsharp
// The "/" endpoint accepts any method.
type Succeeds1 =
    | [<EndPoint "/">] Home
    | [<EndPoint "/about">] About

// The "/" endpoint accepts another method.
type Succeeds2 =
    | [<EndPoint "POST /">] Home
    | [<EndPoint "/about">] About

// The "/about" endpoint also specifies a method.
type Succeeds3 =
    | [<EndPoint "GET /">] Home
    | [<EndPoint "GET /about">] About

// The GET-specified endpoint is on another path than "/"
type Succeeds4 =
    | [<EndPoint "GET /home">] Home
    | [<EndPoint "/about">] About
```

**Comment by Jand42** [comment]
Server-side inferred unions uses a forward-only parsing for performance with some heuristics to look for longer matches first. (One union case parsing a sub-path of another is recommended against.) But when there was a method match, it did not look further, now it is also looking up all non-explicit-method cases for when there is a method match.
