### ISSUE TITLE
Accept string nowarn arguments

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/core#945]
See https://forums.websharper.com/topic/85114

Visual Studio 15.7 and the associated Visual F# Tools now allow passing nowarn arguments as string: `--nowarn:NU1603` in addition to usual int code: `--nowarn:25`. We need to accept these in both wsfsc and zafircs.

As an initial hotfix we can just parse `FS1234` and ignore other string codes. Later we should look into using `WS1234` for our own warnings.

**Comment by RobBarton** [comment]
Thank you, quick work!
