### ISSUE TITLE
MethodAttribute not compiling in C#

### ISSUE THREAD

**Issue by V0d01ey** [dotnet-websharper/core#966]
This is the example from documentation:

* The attribute [Method("GET", "POST", ...)] on a class indicates which methods are accepted by this endpoint. Without this attribute, all methods are accepted.
```csharp	
	[Method("POST")]
	class PostArticle
	{
		int id;
	}

	SiteletBuilder().With<PostArticle>(/* ... */)

	// Accepted Request:    POST /article/12
	// Parsed Endpoint:     new PostArticle { id = 12 }
	// Returned Content:    (determined by .With())
```

But this example does not compile and gives the error:
Error	CS0592	Attribute 'Method' is not valid on this declaration type. It is only valid on 'property, indexer' declarations.

BTW, the Accepted Request seems like having a mistake in docs.

**Comment by Jand42** [comment]
Hi, thanks for the report.

Workaround: use `[EndPoint("POST /")]`.

And indeed, the docs should have `[Method("POST"), EndPoint("article/{id}")]` there, fixing that too.
