### ISSUE TITLE
WebSharper.Json.Serialize and [<Constant>]

### ISSUE THREAD

**Issue by FilippoPolo** [dotnet-websharper/core#992]
Hi all,

I'm trying to use WebSharper.Json.Serialize (from the WebSharper.Web assembly) to reproduce the same serialization format as that generated by using WebSharper.Json.Decode on the client. I'm observing that it does not seem to respect the [Constant] attribute, such that an instance of a type such as:

```
type Chocolate =
  | [<Constant "Dark">] Dark
  | [<Constant "Cinnamon">] Cinnamon
  | [<Constant "Chilli">] Chilli
```

Will get serialized as "{"$":1}" instead of "Cinnamon". Is there anything I can do to make it reproduce the same behavior as client-side serialization?

**Comment by Tarmil** [comment]
This does look like a bug, I'm looking into it.

**Comment by Tarmil** [comment]
I'm failing to reproduce this issue with WebSharper 4.4.0.280. The following code:

```fsharp
open WebSharper

type Chocolate =
  | [<Constant "Dark">] Dark
  | [<Constant "Cinnamon">] Cinnamon
  | [<Constant "Chilli">] Chilli

printfn "%A => %A" Cinnamon (Json.Serialize Cinnamon)
```

prints `Cinnamon => "Cinnamon"` for me. I tried doing so both in a WS.FSharp-compiled and non-WS.FSharp-compiled project, and also in fsi, with the same result. I'm not sure what could be different about your use case that would give this result :/ Can you try to make a minimal failing project? [Here is my minimal successful project.](https://github.com/Tarmil/nofail992)

**Comment by FilippoPolo** [comment]
Thanks for your answer. I'm on holiday at the moment, but I'll get back to you in a couple of weeks or so. Was this behavior changed in a recent update? Maybe I'm just not on the most recent version; I'll need to check.

**Comment by FilippoPolo** [comment]
Turns out there was a specific problem on my side. Everything is working properly now. Thanks!
